In [1]:
import pandas as pd
import time

## Import

In [2]:
clean_df = pd.read_csv("../nyc_traffic_collision_clean.csv")

In [3]:
clean_df.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
0,01/01/2017,3:32,BROOKLYN,11237.0,40.709330,-73.92249,"(40.70933, -73.92249)",JOHNSON AVENUE,SCOTT AVENUE,NaN,...,0,0,0,3,0,Traffic Control Disregarded,Unspecified,3591133,Station Wagon/Sport Utility Vehicle,Sedan
1,01/01/2017,10:20,QUEENS,11372.0,40.751003,-73.89213,"(40.751003, -73.89213)",35 AVENUE,74 STREET,NaN,...,0,0,0,0,0,Unspecified,Unspecified,3596737,Taxi,Taxi
2,01/01/2017,16:15,MANHATTAN,10027.0,40.807770,-73.94549,"(40.80777, -73.94549)",WEST 125 STREET,LENOX AVENUE,NaN,...,0,0,0,0,0,Driver Inattention/Distraction,NaN,3590923,Sedan,NaN
3,01/01/2017,11:01,MANHATTAN,10017.0,40.751120,-73.97127,"(40.75112, -73.97127)",EAST 44 STREET,2 AVENUE,NaN,...,0,0,0,0,0,Driver Inattention/Distraction,Following Too Closely,3590173,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
4,01/01/2017,0:00,BROOKLYN,11210.0,40.632427,-73.94083,"(40.632427, -73.94083)",NaN,NaN,1011 EAST 37 STREET,...,0,0,0,0,0,Unspecified,Unspecified,3821035,Sedan,NaN

# Calculations

### By Borough

Get the number of accidents/collisions by borough

In [4]:
boroughs_df = pd.DataFrame()
boroughs_df["BOROUGH"] = clean_df["BOROUGH"]

In [5]:
boroughs_df.head(100)

      BOROUGH
0    BROOKLYN
1      QUEENS
2   MANHATTAN
3   MANHATTAN
4    BROOKLYN
..        ...
95   BROOKLYN
96     QUEENS
97  MANHATTAN
98  MANHATTAN
99   BROOKLYN

[100 rows x 1 columns]

In [6]:
boroughs_df = boroughs_df.drop_duplicates()

In [7]:
boroughs_df = boroughs_df.reset_index(drop=True)

In [8]:
# Count how many accidents occur in these buroughs
results = []
for i in range(boroughs_df.shape[0]):
    counter = 0
    def countingAccidentsByBorough(row, borough: str):
        global counter
        if row["BOROUGH"] == borough:
            counter += 1
    clean_df.apply(countingAccidentsByBorough, axis=1, args=(boroughs_df.iloc[i]["BOROUGH"], ))
    results.append(counter)
    print("borough: ", boroughs_df.iloc[i]["BOROUGH"], "; total accidents: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_ACCIDENTS_BOROUGH"])
boroughs_df["NUMBER_OF_ACCIDENTS_BOROUGH"] = tempDf["NUMBER_OF_ACCIDENTS_BOROUGH"]

borough:  BROOKLYN ; total accidents:  183473
borough:  QUEENS ; total accidents:  156056
borough:  MANHATTAN ; total accidents:  107136
borough:  BRONX ; total accidents:  90881
borough:  STATEN ISLAND ; total accidents:  20430

In [9]:
boroughs_df.head(5)

         BOROUGH  NUMBER_OF_ACCIDENTS_BOROUGH
0       BROOKLYN                       183473
1         QUEENS                       156056
2      MANHATTAN                       107136
3          BRONX                        90881
4  STATEN ISLAND                        20430

Number of deaths by burough

In [17]:
# Count how many accidents occur in these buroughs
results = []
for i in range(boroughs_df.shape[0]):
    counter = 0
    def countingDeathsByBorough(row, borough: str):
        global counter
        if row["BOROUGH"] == borough:
            counter += row["NUMBER OF PERSONS KILLED"]
    clean_df.apply(countingDeathsByBorough, axis=1, args=(boroughs_df.iloc[i]["BOROUGH"], ))
    results.append(counter)
    print("borough: ", boroughs_df.iloc[i]["BOROUGH"], "; total deaths: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_DEATHS_BOROUGH"])
boroughs_df["NUMBER_OF_DEATHS_BOROUGH"] = tempDf["NUMBER_OF_DEATHS_BOROUGH"]

borough:  BROOKLYN ; total deaths:  230.0
borough:  QUEENS ; total deaths:  201.0
borough:  MANHATTAN ; total deaths:  115.0
borough:  BRONX ; total deaths:  87.0
borough:  STATEN ISLAND ; total deaths:  33.0

In [18]:
boroughs_df.head()

         BOROUGH  NUMBER_OF_ACCIDENTS_BOROUGH  NUMBER_OF_DEATHS_BOROUGH
0       BROOKLYN                       183473                     230.0
1         QUEENS                       156056                     201.0
2      MANHATTAN                       107136                     115.0
3          BRONX                        90881                      87.0
4  STATEN ISLAND                        20430                      33.0

Number of people injusred by borough

In [22]:
# Count how many accidents occur in these buroughs
results = []
for i in range(boroughs_df.shape[0]):
    counter = 0
    def countingInjuriesByBorough(row, borough: str):
        global counter
        if row["BOROUGH"] == borough:
            counter += row["NUMBER OF PERSONS INJURED"]
    clean_df.apply(countingInjuriesByBorough, axis=1, args=(boroughs_df.iloc[i]["BOROUGH"], ))
    results.append(counter)
    print("borough: ", boroughs_df.iloc[i]["BOROUGH"], "; total injuries: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_INJURIES_BOROUGH"])
boroughs_df["NUMBER_OF_INJURIES_BOROUGH"] = tempDf["NUMBER_OF_INJURIES_BOROUGH"]

borough:  BROOKLYN ; total injuries:  58437.0
borough:  QUEENS ; total injuries:  46591.0
borough:  MANHATTAN ; total injuries:  23676.0
borough:  BRONX ; total injuries:  28429.0
borough:  STATEN ISLAND ; total injuries:  6177.0

In [23]:
boroughs_df.head()

,BOROUGH,NUMBER_OF_ACCIDENTS_BOROUGH,NUMBER_OF_DEATHS_BOROUGH,NUMBER_OF_INJURIES_BOROUGH
0,BROOKLYN,183473,230.0,58437.0
1,QUEENS,156056,201.0,46591.0
2,MANHATTAN,107136,115.0,23676.0
3,BRONX,90881,87.0,28429.0
4,STATEN ISLAND,20430,33.0,6177.0

In [29]:
boroughs_df.to_csv("boroughs_calculations.csv")

### By Zip Code

Get the number of accidents/collisions by zip code

In [10]:
zipCodes_df = pd.DataFrame()
zipCodes_df["ZIP CODE"] = clean_df["ZIP CODE"]

In [11]:
zipCodes_df.head(100)

    ZIP CODE
0    11237.0
1    11372.0
2    10027.0
3    10017.0
4    11210.0
..       ...
95   11204.0
96   11413.0
97   10013.0
98   10065.0
99   11223.0

[100 rows x 1 columns]

In [12]:
zipCodes_df = zipCodes_df.drop_duplicates()

In [13]:
zipCodes_df = zipCodes_df.reset_index(drop=True)

In [14]:
zipCodes_df.shape

(227, 1)

In [15]:
# Count how many accidents occur in these zipcodes
results = []
for i in range(zipCodes_df.shape[0]):
    counter = 0
    def countingAccidentsByZipcode(row, zipCode: float):
        global counter
        if row["ZIP CODE"] == zipCode:
            counter += 1
    clean_df.apply(countingAccidentsByZipcode, axis=1, args=(zipCodes_df.iloc[i]["ZIP CODE"], ))
    results.append(counter)
    print("zip code: ", zipCodes_df.iloc[i]["ZIP CODE"], "; total accidents: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_ACCIDENTS_ZIPCODE"])
zipCodes_df["NUMBER_OF_ACCIDENTS_ZIPCODE"] = tempDf["NUMBER_OF_ACCIDENTS_ZIPCODE"]

zip code:  11237.0 ; total accidents:  3587
zip code:  11372.0 ; total accidents:  4541
zip code:  10027.0 ; total accidents:  2922
zip code:  10017.0 ; total accidents:  2974
zip code:  11210.0 ; total accidents:  4999
zip code:  11223.0 ; total accidents:  4521
zip code:  11203.0 ; total accidents:  7656
zip code:  11212.0 ; total accidents:  7763
zip code:  10128.0 ; total accidents:  1949
zip code:  10451.0 ; total accidents:  4404
zip code:  11417.0 ; total accidents:  2942
zip code:  10468.0 ; total accidents:  3570
zip code:  10310.0 ; total accidents:  1800
zip code:  11209.0 ; total accidents:  3440
zip code:  11211.0 ; total accidents:  5585
zip code:  10040.0 ; total accidents:  947
zip code:  11206.0 ; total accidents:  5750
zip code:  11385.0 ; total accidents:  7737
zip code:  11207.0 ; total accidents:  11413
zip code:  11433.0 ; total accidents:  3090
zip code:  10304.0 ; total accidents:  3111
zip code:  10019.0 ; total accidents:  5198
zip code:  11230.0 ; total accidents:  5715
zip code:  11201.0 ; total accidents:  6097
zip code:  10016.0 ; total accidents:  5333
zip code:  11214.0 ; total accidents:  4152
zip code:  10018.0 ; total accidents:  4113
zip code:  10459.0 ; total accidents:  4368
zip code:  11370.0 ; total accidents:  2005
zip code:  10305.0 ; total accidents:  2583
zip code:  11418.0 ; total accidents:  2555
zip code:  11413.0 ; total accidents:  4750
zip code:  10034.0 ; total accidents:  1937
zip code:  11416.0 ; total accidents:  1648
zip code:  11215.0 ; total accidents:  4517
zip code:  11221.0 ; total accidents:  4493
zip code:  11217.0 ; total accidents:  4526
zip code:  10001.0 ; total accidents:  5410
zip code:  10013.0 ; total accidents:  5314
zip code:  11101.0 ; total accidents:  6996
zip code:  11238.0 ; total accidents:  3410
zip code:  10307.0 ; total accidents:  423
zip code:  10002.0 ; total accidents:  5840
zip code:  11421.0 ; total accidents:  2100
zip code:  10472.0 ; total accidents:  3766
zip code:  10011.0 ; total accidents:  3744
zip code:  11229.0 ; total accidents:  4103
zip code:  10466.0 ; total accidents:  5346
zip code:  10036.0 ; total accidents:  5401
zip code:  11435.0 ; total accidents:  4095
zip code:  11434.0 ; total accidents:  7166
zip code:  11208.0 ; total accidents:  7440
zip code:  11378.0 ; total accidents:  3345
zip code:  11375.0 ; total accidents:  3272
zip code:  11422.0 ; total accidents:  3929
zip code:  10469.0 ; total accidents:  4788
zip code:  11365.0 ; total accidents:  1917
zip code:  11354.0 ; total accidents:  4669
zip code:  11428.0 ; total accidents:  1418
zip code:  11228.0 ; total accidents:  2622
zip code:  11429.0 ; total accidents:  2260
zip code:  11105.0 ; total accidents:  1407
zip code:  11204.0 ; total accidents:  3961
zip code:  10065.0 ; total accidents:  3059
zip code:  10457.0 ; total accidents:  5197
zip code:  11420.0 ; total accidents:  4732
zip code:  11355.0 ; total accidents:  3937
zip code:  10014.0 ; total accidents:  1512
zip code:  11235.0 ; total accidents:  5129
zip code:  11373.0 ; total accidents:  5402
zip code:  11233.0 ; total accidents:  6438
zip code:  10452.0 ; total accidents:  3166
zip code:  11414.0 ; total accidents:  1831
zip code:  11377.0 ; total accidents:  5038
zip code:  11004.0 ; total accidents:  1355
zip code:  11432.0 ; total accidents:  4795
zip code:  11236.0 ; total accidents:  8753
zip code:  11427.0 ; total accidents:  1645
zip code:  11001.0 ; total accidents:  257
zip code:  10461.0 ; total accidents:  4191
zip code:  10453.0 ; total accidents:  3628
zip code:  11423.0 ; total accidents:  2124
zip code:  10306.0 ; total accidents:  3514
zip code:  10467.0 ; total accidents:  5825
zip code:  11205.0 ; total accidents:  3157
zip code:  11106.0 ; total accidents:  1890
zip code:  11225.0 ; total accidents:  2932
zip code:  10454.0 ; total accidents:  4142
zip code:  11234.0 ; total accidents:  7924
zip code:  10455.0 ; total accidents:  3721
zip code:  10475.0 ; total accidents:  2557
zip code:  11691.0 ; total accidents:  3318
zip code:  10462.0 ; total accidents:  4115
zip code:  10301.0 ; total accidents:  3007
zip code:  11358.0 ; total accidents:  2256
zip code:  11218.0 ; total accidents:  3965
zip code:  10473.0 ; total accidents:  2966
zip code:  11104.0 ; total accidents:  1187
zip code:  10012.0 ; total accidents:  2798
zip code:  11426.0 ; total accidents:  1263
zip code:  10010.0 ; total accidents:  2696
zip code:  11374.0 ; total accidents:  2119
zip code:  10032.0 ; total accidents:  2914
zip code:  10460.0 ; total accidents:  4721
zip code:  10458.0 ; total accidents:  4500
zip code:  11216.0 ; total accidents:  3513
zip code:  10028.0 ; total accidents:  1471
zip code:  11219.0 ; total accidents:  4527
zip code:  11368.0 ; total accidents:  6120
zip code:  11213.0 ; total accidents:  4199
zip code:  11366.0 ; total accidents:  1314
zip code:  10030.0 ; total accidents:  1269
zip code:  11220.0 ; total accidents:  5020
zip code:  11369.0 ; total accidents:  2809
zip code:  10031.0 ; total accidents:  1518
zip code:  10309.0 ; total accidents:  1336
zip code:  10026.0 ; total accidents:  1526
zip code:  11103.0 ; total accidents:  1740
zip code:  10035.0 ; total accidents:  3906
zip code:  10022.0 ; total accidents:  4798
zip code:  10025.0 ; total accidents:  1964
zip code:  11226.0 ; total accidents:  7297
zip code:  11232.0 ; total accidents:  2557
zip code:  10038.0 ; total accidents:  1290
zip code:  11379.0 ; total accidents:  2174
zip code:  11436.0 ; total accidents:  1490
zip code:  10465.0 ; total accidents:  2669
zip code:  10172.0 ; total accidents:  56
zip code:  11360.0 ; total accidents:  632
zip code:  10009.0 ; total accidents:  1923
zip code:  11412.0 ; total accidents:  2886
zip code:  11693.0 ; total accidents:  775
zip code:  10004.0 ; total accidents:  788
zip code:  10024.0 ; total accidents:  1939
zip code:  11249.0 ; total accidents:  2500
zip code:  10075.0 ; total accidents:  1031
zip code:  10463.0 ; total accidents:  3529
zip code:  10456.0 ; total accidents:  3908
zip code:  11419.0 ; total accidents:  3333
zip code:  10033.0 ; total accidents:  2413
zip code:  10023.0 ; total accidents:  2455
zip code:  10029.0 ; total accidents:  3600
zip code:  11356.0 ; total accidents:  1785
zip code:  11102.0 ; total accidents:  1435
zip code:  11361.0 ; total accidents:  2064
zip code:  10007.0 ; total accidents:  1572
zip code:  10020.0 ; total accidents:  198
zip code:  10021.0 ; total accidents:  1901
zip code:  10003.0 ; total accidents:  3262
zip code:  10308.0 ; total accidents:  1104
zip code:  11364.0 ; total accidents:  1311
zip code:  11367.0 ; total accidents:  2488
zip code:  10005.0 ; total accidents:  482
zip code:  11222.0 ; total accidents:  4014
zip code:  10312.0 ; total accidents:  2464
zip code:  11231.0 ; total accidents:  2594
zip code:  10314.0 ; total accidents:  1028
zip code:  11357.0 ; total accidents:  1800
zip code:  11411.0 ; total accidents:  1983
zip code:  11694.0 ; total accidents:  890
zip code:  11363.0 ; total accidents:  616
zip code:  11362.0 ; total accidents:  946
zip code:  10039.0 ; total accidents:  910
zip code:  10282.0 ; total accidents:  66
zip code:  10037.0 ; total accidents:  1221
zip code:  11695.0 ; total accidents:  3
zip code:  11239.0 ; total accidents:  992
zip code:  10474.0 ; total accidents:  2517
zip code:  10470.0 ; total accidents:  1850
zip code:  11040.0 ; total accidents:  240
zip code:  11224.0 ; total accidents:  2348
zip code:  10471.0 ; total accidents:  1038
zip code:  10006.0 ; total accidents:  440
zip code:  11692.0 ; total accidents:  816
zip code:  11415.0 ; total accidents:  1002
zip code:  11697.0 ; total accidents:  67
zip code:  10464.0 ; total accidents:  399
zip code:  10169.0 ; total accidents:  39
zip code:  10000.0 ; total accidents:  246
zip code:  11430.0 ; total accidents:  142
zip code:  10281.0 ; total accidents:  49
zip code:  10302.0 ; total accidents:  60
zip code:  10280.0 ; total accidents:  102
zip code:  10168.0 ; total accidents:  88
zip code:  10119.0 ; total accidents:  75
zip code:  10123.0 ; total accidents:  24
zip code:  10165.0 ; total accidents:  39
zip code:  10154.0 ; total accidents:  10

zip code:  10120.0 ; total accidents:  13
zip code:  10069.0 ; total accidents:  61
zip code:  10153.0 ; total accidents:  13
zip code:  10170.0 ; total accidents:  8
zip code:  11005.0 ; total accidents:  44
zip code:  10171.0 ; total accidents:  5
zip code:  10121.0 ; total accidents:  67
zip code:  10110.0 ; total accidents:  11
zip code:  10118.0 ; total accidents:  36
zip code:  10105.0 ; total accidents:  17
zip code:  10271.0 ; total accidents:  13
zip code:  10112.0 ; total accidents:  16
zip code:  10174.0 ; total accidents:  5
zip code:  10111.0 ; total accidents:  3
zip code:  10278.0 ; total accidents:  36
zip code:  10151.0 ; total accidents:  3
zip code:  10155.0 ; total accidents:  10
zip code:  10167.0 ; total accidents:  6
zip code:  10041.0 ; total accidents:  16
zip code:  10173.0 ; total accidents:  2
zip code:  10107.0 ; total accidents:  4
zip code:  11109.0 ; total accidents:  16
zip code:  11242.0 ; total accidents:  1
zip code:  10178.0 ; total accidents:  7
zip code:  11241.0 ; total accidents:  1
zip code:  10279.0 ; total accidents:  9
zip code:  10045.0 ; total accidents:  6
zip code:  10152.0 ; total accidents:  4
zip code:  10177.0 ; total accidents:  11
zip code:  11359.0 ; total accidents:  5
zip code:  10103.0 ; total accidents:  8
zip code:  10176.0 ; total accidents:  1
zip code:  10122.0 ; total accidents:  2
zip code:  10158.0 ; total accidents:  2
zip code:  10106.0 ; total accidents:  3
zip code:  10179.0 ; total accidents:  2
zip code:  10115.0 ; total accidents:  3
zip code:  10055.0 ; total accidents:  1
zip code:  11251.0 ; total accidents:  1
Execution time in seconds: 651.1359882354736

In [16]:
zipCodes_df.head()

   ZIP CODE  NUMBER_OF_ACCIDENTS_ZIPCODE
0   11237.0                         3587
1   11372.0                         4541
2   10027.0                         2922
3   10017.0                         2974
4   11210.0                         4999

Number of deaths by zipcode

In [24]:
# Count how many accidents occur in these zipcodes
results = []
for i in range(zipCodes_df.shape[0]):
    counter = 0
    def countingDeathsByZipcode(row, zipCode: float):
        global counter
        if row["ZIP CODE"] == zipCode:
            counter += row["NUMBER OF PERSONS KILLED"]
    clean_df.apply(countingDeathsByZipcode, axis=1, args=(zipCodes_df.iloc[i]["ZIP CODE"], ))
    results.append(counter)
    print("zip code: ", zipCodes_df.iloc[i]["ZIP CODE"], "; total deaths: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_DEATHS_ZIPCODE"])
zipCodes_df["NUMBER_OF_DEATHS_ZIPCODE"] = tempDf["NUMBER_OF_DEATHS_ZIPCODE"]

zip code:  11237.0 ; total deaths:  5.0
zip code:  11372.0 ; total deaths:  6.0
zip code:  10027.0 ; total deaths:  4.0
zip code:  10017.0 ; total deaths:  1.0
zip code:  11210.0 ; total deaths:  2.0
zip code:  11223.0 ; total deaths:  7.0
zip code:  11203.0 ; total deaths:  3.0
zip code:  11212.0 ; total deaths:  10.0
zip code:  10128.0 ; total deaths:  3.0
zip code:  10451.0 ; total deaths:  4.0
zip code:  11417.0 ; total deaths:  4.0
zip code:  10468.0 ; total deaths:  0.0
zip code:  10310.0 ; total deaths:  4.0
zip code:  11209.0 ; total deaths:  5.0
zip code:  11211.0 ; total deaths:  9.0
zip code:  10040.0 ; total deaths:  3.0
zip code:  11206.0 ; total deaths:  11.0
zip code:  11385.0 ; total deaths:  11.0
zip code:  11207.0 ; total deaths:  16.0
zip code:  11433.0 ; total deaths:  4.0
zip code:  10304.0 ; total deaths:  3.0
zip code:  10019.0 ; total deaths:  3.0
zip code:  11230.0 ; total deaths:  4.0
zip code:  11201.0 ; total deaths:  4.0
zip code:  10016.0 ; total deaths:  5.0
zip code:  11214.0 ; total deaths:  7.0
zip code:  10018.0 ; total deaths:  1.0
zip code:  10459.0 ; total deaths:  7.0
zip code:  11370.0 ; total deaths:  2.0
zip code:  10305.0 ; total deaths:  5.0
zip code:  11418.0 ; total deaths:  2.0
zip code:  11413.0 ; total deaths:  8.0
zip code:  10034.0 ; total deaths:  2.0
zip code:  11416.0 ; total deaths:  1.0
zip code:  11215.0 ; total deaths:  7.0
zip code:  11221.0 ; total deaths:  3.0
zip code:  11217.0 ; total deaths:  1.0
zip code:  10001.0 ; total deaths:  5.0
zip code:  10013.0 ; total deaths:  7.0
zip code:  11101.0 ; total deaths:  6.0
zip code:  11238.0 ; total deaths:  2.0
zip code:  10307.0 ; total deaths:  2.0
zip code:  10002.0 ; total deaths:  7.0
zip code:  11421.0 ; total deaths:  4.0
zip code:  10472.0 ; total deaths:  6.0
zip code:  10011.0 ; total deaths:  5.0
zip code:  11229.0 ; total deaths:  7.0
zip code:  10466.0 ; total deaths:  5.0
zip code:  10036.0 ; total deaths:  6.0
zip code:  11435.0 ; total deaths:  4.0
zip code:  11434.0 ; total deaths:  10.0
zip code:  11208.0 ; total deaths:  13.0
zip code:  11378.0 ; total deaths:  2.0
zip code:  11375.0 ; total deaths:  2.0
zip code:  11422.0 ; total deaths:  4.0
zip code:  10469.0 ; total deaths:  2.0
zip code:  11365.0 ; total deaths:  1.0
zip code:  11354.0 ; total deaths:  13.0
zip code:  11428.0 ; total deaths:  1.0
zip code:  11228.0 ; total deaths:  5.0
zip code:  11429.0 ; total deaths:  2.0
zip code:  11105.0 ; total deaths:  2.0
zip code:  11204.0 ; total deaths:  4.0
zip code:  10065.0 ; total deaths:  2.0
zip code:  10457.0 ; total deaths:  6.0
zip code:  11420.0 ; total deaths:  9.0
zip code:  11355.0 ; total deaths:  5.0
zip code:  10014.0 ; total deaths:  8.0
zip code:  11235.0 ; total deaths:  7.0
zip code:  11373.0 ; total deaths:  6.0
zip code:  11233.0 ; total deaths:  12.0
zip code:  10452.0 ; total deaths:  2.0
zip code:  11414.0 ; total deaths:  3.0
zip code:  11377.0 ; total deaths:  7.0
zip code:  11004.0 ; total deaths:  5.0
zip code:  11432.0 ; total deaths:  5.0
zip code:  11236.0 ; total deaths:  19.0
zip code:  11427.0 ; total deaths:  1.0
zip code:  11001.0 ; total deaths:  0.0
zip code:  10461.0 ; total deaths:  4.0
zip code:  10453.0 ; total deaths:  3.0
zip code:  11423.0 ; total deaths:  4.0
zip code:  10306.0 ; total deaths:  4.0
zip code:  10467.0 ; total deaths:  9.0
zip code:  11205.0 ; total deaths:  3.0
zip code:  11106.0 ; total deaths:  5.0
zip code:  11225.0 ; total deaths:  0.0
zip code:  10454.0 ; total deaths:  5.0
zip code:  11234.0 ; total deaths:  18.0
zip code:  10455.0 ; total deaths:  3.0
zip code:  10475.0 ; total deaths:  2.0
zip code:  11691.0 ; total deaths:  7.0
zip code:  10462.0 ; total deaths:  2.0
zip code:  10301.0 ; total deaths:  4.0
zip code:  11358.0 ; total deaths:  1.0
zip code:  11218.0 ; total deaths:  8.0
zip code:  10473.0 ; total deaths:  3.0
zip code:  11104.0 ; total deaths:  1.0
zip code:  10012.0 ; total deaths:  0.0
zip code:  11426.0 ; total deaths:  1.0
zip code:  10010.0 ; total deaths:  3.0
zip code:  11374.0 ; total deaths:  6.0
zip code:  10032.0 ; total deaths:  2.0
zip code:  10460.0 ; total deaths:  4.0
zip code:  10458.0 ; total deaths:  5.0
zip code:  11216.0 ; total deaths:  3.0
zip code:  10028.0 ; total deaths:  1.0
zip code:  11219.0 ; total deaths:  2.0
zip code:  11368.0 ; total deaths:  4.0
zip code:  11213.0 ; total deaths:  5.0
zip code:  11366.0 ; total deaths:  2.0
zip code:  10030.0 ; total deaths:  0.0
zip code:  11220.0 ; total deaths:  7.0
zip code:  11369.0 ; total deaths:  3.0
zip code:  10031.0 ; total deaths:  3.0
zip code:  10309.0 ; total deaths:  2.0
zip code:  10026.0 ; total deaths:  2.0
zip code:  11103.0 ; total deaths:  1.0
zip code:  10035.0 ; total deaths:  6.0
zip code:  10022.0 ; total deaths:  3.0
zip code:  10025.0 ; total deaths:  2.0
zip code:  11226.0 ; total deaths:  5.0
zip code:  11232.0 ; total deaths:  6.0
zip code:  10038.0 ; total deaths:  1.0
zip code:  11379.0 ; total deaths:  5.0
zip code:  11436.0 ; total deaths:  1.0
zip code:  10465.0 ; total deaths:  6.0
zip code:  10172.0 ; total deaths:  0.0
zip code:  11360.0 ; total deaths:  0.0
zip code:  10009.0 ; total deaths:  1.0
zip code:  11412.0 ; total deaths:  3.0
zip code:  11693.0 ; total deaths:  3.0
zip code:  10004.0 ; total deaths:  0.0
zip code:  10024.0 ; total deaths:  1.0
zip code:  11249.0 ; total deaths:  1.0
zip code:  10075.0 ; total deaths:  3.0
zip code:  10463.0 ; total deaths:  5.0
zip code:  10456.0 ; total deaths:  0.0
zip code:  11419.0 ; total deaths:  4.0
zip code:  10033.0 ; total deaths:  2.0
zip code:  10023.0 ; total deaths:  5.0
zip code:  10029.0 ; total deaths:  6.0
zip code:  11356.0 ; total deaths:  1.0
zip code:  11102.0 ; total deaths:  1.0
zip code:  11361.0 ; total deaths:  1.0
zip code:  10007.0 ; total deaths:  0.0
zip code:  10020.0 ; total deaths:  0.0
zip code:  10021.0 ; total deaths:  5.0
zip code:  10003.0 ; total deaths:  3.0
zip code:  10308.0 ; total deaths:  0.0
zip code:  11364.0 ; total deaths:  3.0
zip code:  11367.0 ; total deaths:  5.0
zip code:  10005.0 ; total deaths:  0.0
zip code:  11222.0 ; total deaths:  7.0
zip code:  10312.0 ; total deaths:  7.0
zip code:  11231.0 ; total deaths:  1.0
zip code:  10314.0 ; total deaths:  2.0
zip code:  11357.0 ; total deaths:  1.0
zip code:  11411.0 ; total deaths:  1.0
zip code:  11694.0 ; total deaths:  1.0
zip code:  11363.0 ; total deaths:  0.0
zip code:  11362.0 ; total deaths:  1.0
zip code:  10039.0 ; total deaths:  1.0
zip code:  10282.0 ; total deaths:  0.0
zip code:  10037.0 ; total deaths:  1.0
zip code:  11695.0 ; total deaths:  0.0
zip code:  11239.0 ; total deaths:  0.0
zip code:  10474.0 ; total deaths:  2.0
zip code:  10470.0 ; total deaths:  0.0
zip code:  11040.0 ; total deaths:  0.0
zip code:  11224.0 ; total deaths:  1.0
zip code:  10471.0 ; total deaths:  2.0
zip code:  10006.0 ; total deaths:  0.0
zip code:  11692.0 ; total deaths:  1.0
zip code:  11415.0 ; total deaths:  3.0
zip code:  11697.0 ; total deaths:  0.0
zip code:  10464.0 ; total deaths:  0.0
zip code:  10169.0 ; total deaths:  0.0
zip code:  10000.0 ; total deaths:  0.0
zip code:  11430.0 ; total deaths:  0.0
zip code:  10281.0 ; total deaths:  1.0
zip code:  10302.0 ; total deaths:  0.0
zip code:  10280.0 ; total deaths:  1.0
zip code:  10168.0 ; total deaths:  0.0
zip code:  10119.0 ; total deaths:  0.0
zip code:  10123.0 ; total deaths:  0.0
zip code:  10165.0 ; total deaths:  0.0
zip code:  10154.0 ; total deaths:  0.0
zip code:  10120.0 ; total deaths:  0.0
zip code:  10069.0 ; total deaths:  0.0
zip code:  10153.0 ; total deaths:  0.0
zip code:  10170.0 ; total deaths:  0.0
zip code:  11005.0 ; total deaths:  1.0
zip code:  10171.0 ; total deaths:  0.0
zip code:  10121.0 ; total deaths:  0.0
zip code:  10110.0 ; total deaths:  0.0
zip code:  10118.0 ; total deaths:  0.0
zip code:  10105.0 ; total deaths:  0.0
zip code:  10271.0 ; total deaths:  0.0
zip code:  10112.0 ; total deaths:  0.0
zip code:  10174.0 ; total deaths:  0.0
zip code:  10111.0 ; total deaths:  0.0
zip code:  10278.0 ; total deaths:  0.0
zip code:  10151.0 ; total deaths:  0.0
zip code:  10155.0 ; total deaths:  0.0

zip code:  10167.0 ; total deaths:  0.0
zip code:  10041.0 ; total deaths:  0.0
zip code:  10173.0 ; total deaths:  0.0
zip code:  10107.0 ; total deaths:  0.0
zip code:  11109.0 ; total deaths:  0.0
zip code:  11242.0 ; total deaths:  0.0
zip code:  10178.0 ; total deaths:  0.0
zip code:  11241.0 ; total deaths:  0.0
zip code:  10279.0 ; total deaths:  0.0
zip code:  10045.0 ; total deaths:  0.0
zip code:  10152.0 ; total deaths:  0.0
zip code:  10177.0 ; total deaths:  0.0
zip code:  11359.0 ; total deaths:  0.0
zip code:  10103.0 ; total deaths:  0.0
zip code:  10176.0 ; total deaths:  0.0
zip code:  10122.0 ; total deaths:  0.0
zip code:  10158.0 ; total deaths:  0.0
zip code:  10106.0 ; total deaths:  0.0
zip code:  10179.0 ; total deaths:  0.0
zip code:  10115.0 ; total deaths:  0.0
zip code:  10055.0 ; total deaths:  0.0
zip code:  11251.0 ; total deaths:  0.0

In [25]:
zipCodes_df.head()

   ZIP CODE  NUMBER_OF_ACCIDENTS_ZIPCODE  NUMBER_OF_DEATHS_ZIPCODE
0   11237.0                         3587                       5.0
1   11372.0                         4541                       6.0
2   10027.0                         2922                       4.0
3   10017.0                         2974                       1.0
4   11210.0                         4999                       2.0

Number of injuries by zipcode

In [26]:
# Count how many accidents occur in these zipcodes
results = []
for i in range(zipCodes_df.shape[0]):
    counter = 0
    def countingInjuriesByZipcode(row, zipCode: float):
        global counter
        if row["ZIP CODE"] == zipCode:
            counter += row["NUMBER OF PERSONS INJURED"]
    clean_df.apply(countingInjuriesByZipcode, axis=1, args=(zipCodes_df.iloc[i]["ZIP CODE"], ))
    results.append(counter)
    print("zip code: ", zipCodes_df.iloc[i]["ZIP CODE"], "; total injuries: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_INJURIES_ZIPCODE"])
zipCodes_df["NUMBER_OF_INJURIES_ZIPCODE"] = tempDf["NUMBER_OF_INJURIES_ZIPCODE"]

zip code:  11237.0 ; total injuries:  904.0
zip code:  11372.0 ; total injuries:  1323.0
zip code:  10027.0 ; total injuries:  906.0
zip code:  10017.0 ; total injuries:  723.0
zip code:  11210.0 ; total injuries:  1856.0
zip code:  11223.0 ; total injuries:  1399.0
zip code:  11203.0 ; total injuries:  3287.0
zip code:  11212.0 ; total injuries:  3160.0
zip code:  10128.0 ; total injuries:  429.0
zip code:  10451.0 ; total injuries:  1463.0
zip code:  11417.0 ; total injuries:  985.0
zip code:  10468.0 ; total injuries:  1256.0
zip code:  10310.0 ; total injuries:  618.0
zip code:  11209.0 ; total injuries:  829.0
zip code:  11211.0 ; total injuries:  1521.0
zip code:  10040.0 ; total injuries:  269.0
zip code:  11206.0 ; total injuries:  1771.0
zip code:  11385.0 ; total injuries:  2117.0
zip code:  11207.0 ; total injuries:  4160.0
zip code:  11433.0 ; total injuries:  1085.0
zip code:  10304.0 ; total injuries:  998.0
zip code:  10019.0 ; total injuries:  952.0
zip code:  11230.0 ; total injuries:  1676.0
zip code:  11201.0 ; total injuries:  1368.0
zip code:  10016.0 ; total injuries:  1308.0
zip code:  11214.0 ; total injuries:  1029.0
zip code:  10018.0 ; total injuries:  619.0
zip code:  10459.0 ; total injuries:  1399.0
zip code:  11370.0 ; total injuries:  575.0
zip code:  10305.0 ; total injuries:  721.0
zip code:  11418.0 ; total injuries:  641.0
zip code:  11413.0 ; total injuries:  1849.0
zip code:  10034.0 ; total injuries:  574.0
zip code:  11416.0 ; total injuries:  545.0
zip code:  11215.0 ; total injuries:  1075.0
zip code:  11221.0 ; total injuries:  1440.0
zip code:  11217.0 ; total injuries:  1135.0
zip code:  10001.0 ; total injuries:  858.0
zip code:  10013.0 ; total injuries:  924.0
zip code:  11101.0 ; total injuries:  1768.0
zip code:  11238.0 ; total injuries:  1176.0
zip code:  10307.0 ; total injuries:  82.0
zip code:  10002.0 ; total injuries:  1595.0
zip code:  11421.0 ; total injuries:  622.0
zip code:  10472.0 ; total injuries:  1086.0
zip code:  10011.0 ; total injuries:  635.0
zip code:  11229.0 ; total injuries:  1344.0
zip code:  10466.0 ; total injuries:  1875.0
zip code:  10036.0 ; total injuries:  901.0
zip code:  11435.0 ; total injuries:  1368.0
zip code:  11434.0 ; total injuries:  2521.0
zip code:  11208.0 ; total injuries:  2608.0
zip code:  11378.0 ; total injuries:  788.0
zip code:  11375.0 ; total injuries:  914.0
zip code:  11422.0 ; total injuries:  1598.0
zip code:  10469.0 ; total injuries:  2002.0
zip code:  11365.0 ; total injuries:  456.0
zip code:  11354.0 ; total injuries:  1073.0
zip code:  11428.0 ; total injuries:  453.0
zip code:  11228.0 ; total injuries:  834.0
zip code:  11429.0 ; total injuries:  855.0
zip code:  11105.0 ; total injuries:  362.0
zip code:  11204.0 ; total injuries:  1268.0
zip code:  10065.0 ; total injuries:  498.0
zip code:  10457.0 ; total injuries:  1698.0
zip code:  11420.0 ; total injuries:  1638.0
zip code:  11355.0 ; total injuries:  999.0
zip code:  10014.0 ; total injuries:  289.0
zip code:  11235.0 ; total injuries:  1343.0
zip code:  11373.0 ; total injuries:  1285.0
zip code:  11233.0 ; total injuries:  2220.0
zip code:  10452.0 ; total injuries:  893.0
zip code:  11414.0 ; total injuries:  552.0
zip code:  11377.0 ; total injuries:  1562.0
zip code:  11004.0 ; total injuries:  418.0
zip code:  11432.0 ; total injuries:  1356.0
zip code:  11236.0 ; total injuries:  3740.0
zip code:  11427.0 ; total injuries:  485.0
zip code:  11001.0 ; total injuries:  69.0
zip code:  10461.0 ; total injuries:  1235.0
zip code:  10453.0 ; total injuries:  1314.0
zip code:  11423.0 ; total injuries:  694.0
zip code:  10306.0 ; total injuries:  1103.0
zip code:  10467.0 ; total injuries:  1757.0
zip code:  11205.0 ; total injuries:  881.0
zip code:  11106.0 ; total injuries:  583.0
zip code:  11225.0 ; total injuries:  1028.0
zip code:  10454.0 ; total injuries:  1398.0
zip code:  11234.0 ; total injuries:  2704.0
zip code:  10455.0 ; total injuries:  1303.0
zip code:  10475.0 ; total injuries:  705.0
zip code:  11691.0 ; total injuries:  866.0
zip code:  10462.0 ; total injuries:  1134.0
zip code:  10301.0 ; total injuries:  862.0
zip code:  11358.0 ; total injuries:  671.0
zip code:  11218.0 ; total injuries:  1211.0
zip code:  10473.0 ; total injuries:  803.0
zip code:  11104.0 ; total injuries:  393.0
zip code:  10012.0 ; total injuries:  600.0
zip code:  11426.0 ; total injuries:  349.0
zip code:  10010.0 ; total injuries:  721.0
zip code:  11374.0 ; total injuries:  593.0
zip code:  10032.0 ; total injuries:  684.0
zip code:  10460.0 ; total injuries:  1495.0
zip code:  10458.0 ; total injuries:  1280.0
zip code:  11216.0 ; total injuries:  1188.0
zip code:  10028.0 ; total injuries:  316.0
zip code:  11219.0 ; total injuries:  1281.0
zip code:  11368.0 ; total injuries:  1909.0
zip code:  11213.0 ; total injuries:  1496.0
zip code:  11366.0 ; total injuries:  413.0
zip code:  10030.0 ; total injuries:  381.0
zip code:  11220.0 ; total injuries:  1405.0
zip code:  11369.0 ; total injuries:  884.0
zip code:  10031.0 ; total injuries:  412.0
zip code:  10309.0 ; total injuries:  389.0
zip code:  10026.0 ; total injuries:  488.0
zip code:  11103.0 ; total injuries:  515.0
zip code:  10035.0 ; total injuries:  1123.0
zip code:  10022.0 ; total injuries:  955.0
zip code:  10025.0 ; total injuries:  410.0
zip code:  11226.0 ; total injuries:  2735.0
zip code:  11232.0 ; total injuries:  752.0
zip code:  10038.0 ; total injuries:  240.0
zip code:  11379.0 ; total injuries:  640.0
zip code:  11436.0 ; total injuries:  574.0
zip code:  10465.0 ; total injuries:  705.0
zip code:  10172.0 ; total injuries:  7.0
zip code:  11360.0 ; total injuries:  135.0
zip code:  10009.0 ; total injuries:  523.0
zip code:  11412.0 ; total injuries:  1163.0
zip code:  11693.0 ; total injuries:  252.0
zip code:  10004.0 ; total injuries:  124.0
zip code:  10024.0 ; total injuries:  407.0
zip code:  11249.0 ; total injuries:  578.0
zip code:  10075.0 ; total injuries:  191.0
zip code:  10463.0 ; total injuries:  842.0
zip code:  10456.0 ; total injuries:  1236.0
zip code:  11419.0 ; total injuries:  1059.0
zip code:  10033.0 ; total injuries:  581.0
zip code:  10023.0 ; total injuries:  474.0
zip code:  10029.0 ; total injuries:  951.0
zip code:  11356.0 ; total injuries:  353.0
zip code:  11102.0 ; total injuries:  375.0
zip code:  11361.0 ; total injuries:  386.0
zip code:  10007.0 ; total injuries:  358.0
zip code:  10020.0 ; total injuries:  42.0
zip code:  10021.0 ; total injuries:  342.0
zip code:  10003.0 ; total injuries:  824.0
zip code:  10308.0 ; total injuries:  357.0
zip code:  11364.0 ; total injuries:  244.0
zip code:  11367.0 ; total injuries:  612.0
zip code:  10005.0 ; total injuries:  78.0
zip code:  11222.0 ; total injuries:  733.0
zip code:  10312.0 ; total injuries:  695.0
zip code:  11231.0 ; total injuries:  470.0
zip code:  10314.0 ; total injuries:  327.0
zip code:  11357.0 ; total injuries:  493.0
zip code:  11411.0 ; total injuries:  936.0
zip code:  11694.0 ; total injuries:  257.0
zip code:  11363.0 ; total injuries:  141.0
zip code:  11362.0 ; total injuries:  201.0
zip code:  10039.0 ; total injuries:  250.0
zip code:  10282.0 ; total injuries:  5.0
zip code:  10037.0 ; total injuries:  381.0
zip code:  11695.0 ; total injuries:  3.0
zip code:  11239.0 ; total injuries:  252.0
zip code:  10474.0 ; total injuries:  502.0
zip code:  10470.0 ; total injuries:  612.0
zip code:  11040.0 ; total injuries:  71.0
zip code:  11224.0 ; total injuries:  632.0
zip code:  10471.0 ; total injuries:  272.0
zip code:  10006.0 ; total injuries:  97.0
zip code:  11692.0 ; total injuries:  239.0
zip code:  11415.0 ; total injuries:  216.0
zip code:  11697.0 ; total injuries:  13.0
zip code:  10464.0 ; total injuries:  164.0
zip code:  10169.0 ; total injuries:  12.0
zip code:  10000.0 ; total injuries:  84.0
zip code:  11430.0 ; total injuries:  34.0
zip code:  10281.0 ; total injuries:  5.0
zip code:  10302.0 ; total injuries:  25.0
zip code:  10280.0 ; total injuries:  21.0
zip code:  10168.0 ; total injuries:  16.0
zip code:  10119.0 ; total injuries:  13.0
zip code:  10123.0 ; total injuries:  4.0

zip code:  10165.0 ; total injuries:  5.0
zip code:  10154.0 ; total injuries:  0.0
zip code:  10120.0 ; total injuries:  3.0
zip code:  10069.0 ; total injuries:  12.0
zip code:  10153.0 ; total injuries:  1.0
zip code:  10170.0 ; total injuries:  1.0
zip code:  11005.0 ; total injuries:  7.0
zip code:  10171.0 ; total injuries:  0.0
zip code:  10121.0 ; total injuries:  7.0
zip code:  10110.0 ; total injuries:  3.0
zip code:  10118.0 ; total injuries:  2.0
zip code:  10105.0 ; total injuries:  3.0
zip code:  10271.0 ; total injuries:  5.0
zip code:  10112.0 ; total injuries:  3.0
zip code:  10174.0 ; total injuries:  0.0
zip code:  10111.0 ; total injuries:  0.0
zip code:  10278.0 ; total injuries:  11.0
zip code:  10151.0 ; total injuries:  0.0
zip code:  10155.0 ; total injuries:  2.0
zip code:  10167.0 ; total injuries:  2.0
zip code:  10041.0 ; total injuries:  1.0
zip code:  10173.0 ; total injuries:  0.0
zip code:  10107.0 ; total injuries:  2.0
zip code:  11109.0 ; total injuries:  2.0
zip code:  11242.0 ; total injuries:  0.0
zip code:  10178.0 ; total injuries:  2.0
zip code:  11241.0 ; total injuries:  0.0
zip code:  10279.0 ; total injuries:  0.0
zip code:  10045.0 ; total injuries:  2.0
zip code:  10152.0 ; total injuries:  0.0
zip code:  10177.0 ; total injuries:  2.0
zip code:  11359.0 ; total injuries:  0.0
zip code:  10103.0 ; total injuries:  3.0
zip code:  10176.0 ; total injuries:  1.0
zip code:  10122.0 ; total injuries:  2.0
zip code:  10158.0 ; total injuries:  0.0
zip code:  10106.0 ; total injuries:  1.0
zip code:  10179.0 ; total injuries:  0.0
zip code:  10115.0 ; total injuries:  0.0
zip code:  10055.0 ; total injuries:  0.0
zip code:  11251.0 ; total injuries:  1.0

In [27]:
zipCodes_df.head()

,ZIP CODE,NUMBER_OF_ACCIDENTS_ZIPCODE,NUMBER_OF_DEATHS_ZIPCODE,NUMBER_OF_INJURIES_ZIPCODE
0,11237.0,3587,5.0,904.0
1,11372.0,4541,6.0,1323.0
2,10027.0,2922,4.0,906.0
3,10017.0,2974,1.0,723.0
4,11210.0,4999,2.0,1856.0

In [28]:
zipCodes_df.to_csv("zipCode_calculations.csv")

## About the Vehicle(s)

In [54]:
tempDf1 = pd.DataFrame()
tempDf2 = pd.DataFrame()

tempDf1["VEHICLES"] = clean_df["VEHICLE TYPE CODE 1"]
tempDf2["VEHICLES"] = clean_df["VEHICLE TYPE CODE 2"]

In [55]:
vehicles_df = pd.concat([tempDf1, tempDf2], ignore_index=True)

In [56]:
vehicles_df = vehicles_df.dropna()

In [57]:
vehicles_df = vehicles_df.drop_duplicates()

In [58]:
vehicles_df = vehicles_df.reset_index(drop=True)

In [67]:
vehicles_df.shape

(1443, 1)

## Takes a long time!

Count the number of collisions by vehicle type

In [70]:
# Count how many accidents occur by vehicle type
# Because there are two columns for vehicles, you'll need to take both columns in
startTime = time.time()


results = []
for i in range(vehicles_df.shape[0]):
    counter = 0
    def countingAccidentsByVehicle(row, vehicle: str):
        global counter
        if row["VEHICLE TYPE CODE 1"] == vehicle and row["VEHICLE TYPE CODE 2"] == vehicle:
            #print("\nvehicle: ", vehicles_df.iloc[i]["VEHICLES"], "\nvehicle 1: ", row["VEHICLE TYPE CODE 1"], "\nvehicle 2: ", row["VEHICLE TYPE CODE 2"], "\ncounting up 2", "\n========")
            counter += 2
        elif row["VEHICLE TYPE CODE 1"] == vehicle or row["VEHICLE TYPE CODE 2"] == vehicle:
            #print("\nvehicle: ", vehicles_df.iloc[i]["VEHICLES"], "\nvehicle 1: ", row["VEHICLE TYPE CODE 1"], "\nvehicle 2: ", row["VEHICLE TYPE CODE 2"], "\ncounting up 1", "\n========")
            counter += 1
        
    clean_df.apply(countingAccidentsByVehicle, axis=1, args=(vehicles_df.iloc[i]["VEHICLES"], ))
    results.append(counter)
    print("index: ", i, "; vehicle: ", vehicles_df.iloc[i]["VEHICLES"], "; total accidents: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_ACCIDENTS_VEHICLE"])
vehicles_df["NUMBER_OF_ACCIDENTS_VEHICLE"] = tempDf["NUMBER_OF_ACCIDENTS_VEHICLE"]


executionTime = (time.time() - startTime)
print('Execution time in seconds: ' + str(executionTime))

index:  0 ; vehicle:  Station Wagon/Sport Utility Vehicle ; total accidents:  336486
index:  1 ; vehicle:  Taxi ; total accidents:  42181
index:  2 ; vehicle:  Sedan ; total accidents:  441850
index:  3 ; vehicle:  Tractor Truck Diesel ; total accidents:  6429
index:  4 ; vehicle:  Bus ; total accidents:  17687
index:  5 ; vehicle:  Garbage or Refuse ; total accidents:  1968
index:  6 ; vehicle:  FIRET ; total accidents:  50
index:  7 ; vehicle:  PK ; total accidents:  1855
index:  8 ; vehicle:  Motorcycle ; total accidents:  5504
index:  9 ; vehicle:  Convertible ; total accidents:  2611
index:  10 ; vehicle:  Bike ; total accidents:  20052
index:  11 ; vehicle:  Ambulance ; total accidents:  2985
index:  12 ; vehicle:  Refrigerated Van ; total accidents:  418
index:  13 ; vehicle:  Box Truck ; total accidents:  23703
index:  14 ; vehicle:  Van ; total accidents:  7405
index:  15 ; vehicle:  Pick-up Truck ; total accidents:  29064
index:  16 ; vehicle:  Carry All ; total accidents:  1612
index:  17 ; vehicle:  SUB ; total accidents:  1
index:  18 ; vehicle:  Tow Truck / Wrecker ; total accidents:  1029
index:  19 ; vehicle:  Armored Truck ; total accidents:  326
index:  20 ; vehicle:  Tanker ; total accidents:  616
index:  21 ; vehicle:  Tractor Truck Gasoline ; total accidents:  1176
index:  22 ; vehicle:  usps ; total accidents:  17
index:  23 ; vehicle:  4 dr sedan ; total accidents:  458
index:  24 ; vehicle:  bus ; total accidents:  30
index:  25 ; vehicle:  Flat Bed ; total accidents:  1848
index:  26 ; vehicle:  AMBUL ; total accidents:  309
index:  27 ; vehicle:  OLC ; total accidents:  1
index:  28 ; vehicle:  Dump ; total accidents:  3101
index:  29 ; vehicle:  GARBA ; total accidents:  16
index:  30 ; vehicle:  Concrete Mixer ; total accidents:  416
index:  31 ; vehicle:  DUMP ; total accidents:  93
index:  32 ; vehicle:  Lunch Wagon ; total accidents:  30
index:  33 ; vehicle:  FIRE ; total accidents:  176
index:  34 ; vehicle:  atv p ; total accidents:  1
index:  35 ; vehicle:  CRANE ; total accidents:  11
index:  36 ; vehicle:  2 dr sedan ; total accidents:  41
index:  37 ; vehicle:  BOX T ; total accidents:  46
index:  38 ; vehicle:  TRUCK ; total accidents:  187
index:  39 ; vehicle:  3-Door ; total accidents:  244
index:  40 ; vehicle:  van ; total accidents:  311
index:  41 ; vehicle:  COMME ; total accidents:  31
index:  42 ; vehicle:  Stake or Rack ; total accidents:  120
index:  43 ; vehicle:  FUEL ; total accidents:  2
index:  44 ; vehicle:  Pickup with mounted Camper ; total accidents:  47
index:  45 ; vehicle:  Multi-Wheeled Vehicle ; total accidents:  86
index:  46 ; vehicle:  other ; total accidents:  1
index:  47 ; vehicle:  PAS ; total accidents:  20
index:  48 ; vehicle:  moped ; total accidents:  35
index:  49 ; vehicle:  Chassis Cab ; total accidents:  528
index:  50 ; vehicle:  MACK ; total accidents:  17
index:  51 ; vehicle:  self ; total accidents:  5
index:  52 ; vehicle:  Moped ; total accidents:  1001
index:  53 ; vehicle:  firet ; total accidents:  15
index:  54 ; vehicle:  School Bus ; total accidents:  177
index:  55 ; vehicle:  Deliv ; total accidents:  6
index:  56 ; vehicle:  subn ; total accidents:  10
index:  57 ; vehicle:  DELV ; total accidents:  42
index:  58 ; vehicle:  Motorbike ; total accidents:  498
index:  59 ; vehicle:  SANIT ; total accidents:  18
index:  60 ; vehicle:  trail ; total accidents:  56
index:  61 ; vehicle:  3DOOR ; total accidents:  1
index:  62 ; vehicle:  TRAC. ; total accidents:  1
index:  63 ; vehicle:  power ; total accidents:  5
index:  64 ; vehicle:  TANK ; total accidents:  16
index:  65 ; vehicle:  fire ; total accidents:  42
index:  66 ; vehicle:  rmp ; total accidents:  1
index:  67 ; vehicle:  cemen ; total accidents:  2
index:  68 ; vehicle:  OTHER ; total accidents:  4
index:  69 ; vehicle:  Fire ; total accidents:  43
index:  70 ; vehicle:  Flat ; total accidents:  5
index:  71 ; vehicle:  TRACT ; total accidents:  57
index:  72 ; vehicle:  TRK ; total accidents:  22
index:  73 ; vehicle:  Beverage Truck ; total accidents:  264
index:  74 ; vehicle:  PC ; total accidents:  8
index:  75 ; vehicle:  Bulk Agriculture ; total accidents:  71
index:  76 ; vehicle:  Motorized Home ; total accidents:  28
index:  77 ; vehicle:  SCHOO ; total accidents:  49
index:  78 ; vehicle:  FDNY ; total accidents:  145
index:  79 ; vehicle:  Flat Rack ; total accidents:  248
index:  80 ; vehicle:  UTILI ; total accidents:  28
index:  81 ; vehicle:  Motor Home ; total accidents:  4
index:  82 ; vehicle:  OMNIB ; total accidents:  3
index:  83 ; vehicle:  Lift Boom ; total accidents:  182
index:  84 ; vehicle:  EMS T ; total accidents:  1
index:  85 ; vehicle:  TRAIL ; total accidents:  152
index:  86 ; vehicle:  dump ; total accidents:  17
index:  87 ; vehicle:  Pedicab ; total accidents:  83
index:  88 ; vehicle:  van t ; total accidents:  3
index:  89 ; vehicle:  Self ; total accidents:  4
index:  90 ; vehicle:  Ambul ; total accidents:  66
index:  91 ; vehicle:  tow t ; total accidents:  13
index:  92 ; vehicle:  USPS ; total accidents:  74
index:  93 ; vehicle:  DELIV ; total accidents:  43
index:  94 ; vehicle:  FORKL ; total accidents:  62
index:  95 ; vehicle:  Stake ; total accidents:  1
index:  96 ; vehicle:  Utili ; total accidents:  5
index:  97 ; vehicle:  COMM ; total accidents:  5
index:  98 ; vehicle:  ELECT ; total accidents:  52
index:  99 ; vehicle:  Snow Plow ; total accidents:  106
index:  100 ; vehicle:  fdny ; total accidents:  17
index:  101 ; vehicle:  Tow Truck ; total accidents:  28
index:  102 ; vehicle:  UNKNO ; total accidents:  85
index:  103 ; vehicle:  tract ; total accidents:  19
index:  104 ; vehicle:  schoo ; total accidents:  15
index:  105 ; vehicle:  Trail ; total accidents:  30
index:  106 ; vehicle:  fedx ; total accidents:  1
index:  107 ; vehicle:  YELLO ; total accidents:  10
index:  108 ; vehicle:  amb ; total accidents:  3
index:  109 ; vehicle:  Livestock Rack ; total accidents:  15
index:  110 ; vehicle:  SEMI ; total accidents:  7
index:  111 ; vehicle:  stree ; total accidents:  9
index:  112 ; vehicle:  AMBU ; total accidents:  66
index:  113 ; vehicle:  Schoo ; total accidents:  8
index:  114 ; vehicle:  FLEET ; total accidents:  2
index:  115 ; vehicle:  US ; total accidents:  1
index:  116 ; vehicle:  Backh ; total accidents:  2
index:  117 ; vehicle:  ambul ; total accidents:  76
index:  118 ; vehicle:  Budge ; total accidents:  2
index:  119 ; vehicle:  E-Bik ; total accidents:  168
index:  120 ; vehicle:  FORK ; total accidents:  19
index:  121 ; vehicle:  Flatb ; total accidents:  1
index:  122 ; vehicle:  Box T ; total accidents:  7
index:  123 ; vehicle:  PASS ; total accidents:  3
index:  124 ; vehicle:  SUV ; total accidents:  7
index:  125 ; vehicle:  marke ; total accidents:  1
index:  126 ; vehicle:  Minicycle ; total accidents:  25
index:  127 ; vehicle:  miniv ; total accidents:  1
index:  128 ; vehicle:  COM ; total accidents:  42
index:  129 ; vehicle:  ROOD ; total accidents:  1
index:  130 ; vehicle:  box t ; total accidents:  16
index:  131 ; vehicle:  tow ; total accidents:  10
index:  132 ; vehicle:  ROAD ; total accidents:  8
index:  133 ; vehicle:  UNK ; total accidents:  88
index:  134 ; vehicle:  BACK ; total accidents:  6
index:  135 ; vehicle:  SYBN ; total accidents:  1
index:  136 ; vehicle:  tr ; total accidents:  5
index:  137 ; vehicle:  USPS # 487 ; total accidents:  1
index:  138 ; vehicle:  4D ; total accidents:  2
index:  139 ; vehicle:  trac ; total accidents:  1
index:  140 ; vehicle:  ?omme ; total accidents:  1
index:  141 ; vehicle:  pas ; total accidents:  4
index:  142 ; vehicle:  STREE ; total accidents:  21
index:  143 ; vehicle:  FREIG ; total accidents:  17
index:  144 ; vehicle:  Vanette ; total accidents:  15
index:  145 ; vehicle:  AMB ; total accidents:  32
index:  146 ; vehicle:  SCOO ; total accidents:  1
index:  147 ; vehicle:  ambu ; total accidents:  15
index:  148 ; vehicle:  UTLIT ; total accidents:  1
index:  149 ; vehicle:  FORD ; total accidents:  13
index:  150 ; vehicle:  KP160 ; total accidents:  1
index:  151 ; vehicle:  plow ; total accidents:  1
index:  152 ; vehicle:  TOW T ; total accidents:  42

index:  153 ; vehicle:  ladde ; total accidents:  1
index:  154 ; vehicle:  Forkl ; total accidents:  11
index:  155 ; vehicle:  FEDEX ; total accidents:  5
index:  156 ; vehicle:  AMBULANCE ; total accidents:  231
index:  157 ; vehicle:  Motorscooter ; total accidents:  603
index:  158 ; vehicle:  TRL ; total accidents:  11
index:  159 ; vehicle:  Subur ; total accidents:  1
index:  160 ; vehicle:  4 RUN ; total accidents:  1
index:  161 ; vehicle:  Power ; total accidents:  1
index:  162 ; vehicle:  backh ; total accidents:  5
index:  163 ; vehicle:  POWER ; total accidents:  21
index:  164 ; vehicle:  com ; total accidents:  12
index:  165 ; vehicle:  MOPED ; total accidents:  121
index:  166 ; vehicle:  TLC ; total accidents:  1
index:  167 ; vehicle:  fork ; total accidents:  11
index:  168 ; vehicle:  dodge ; total accidents:  1
index:  169 ; vehicle:  motor ; total accidents:  8
index:  170 ; vehicle:  ARMOR ; total accidents:  4
index:  171 ; vehicle:  VAB ; total accidents:  1
index:  172 ; vehicle:  Well Driller ; total accidents:  9
index:  173 ; vehicle:  SW ; total accidents:  1
index:  174 ; vehicle:  util ; total accidents:  4
index:  175 ; vehicle:  OMT ; total accidents:  2
index:  176 ; vehicle:  deliv ; total accidents:  11
index:  177 ; vehicle:  Shove ; total accidents:  1
index:  178 ; vehicle:  SEDAN ; total accidents:  3
index:  179 ; vehicle:  Pallet ; total accidents:  44
index:  180 ; vehicle:  KENWO ; total accidents:  3
index:  181 ; vehicle:  OML ; total accidents:  4
index:  182 ; vehicle:  unkno ; total accidents:  24
index:  183 ; vehicle:  ESU T ; total accidents:  2
index:  184 ; vehicle:  18 WH ; total accidents:  2
index:  185 ; vehicle:  WAGON ; total accidents:  6
index:  186 ; vehicle:  TANKE ; total accidents:  4
index:  187 ; vehicle:  REPAI ; total accidents:  1
index:  188 ; vehicle:  RV ; total accidents:  17
index:  189 ; vehicle:  winne ; total accidents:  1
index:  190 ; vehicle:  p/sh ; total accidents:  4
index:  191 ; vehicle:  UTIL ; total accidents:  31
index:  192 ; vehicle:  REFG ; total accidents:  14
index:  193 ; vehicle:  SCOOT ; total accidents:  55
index:  194 ; vehicle:  4DS ; total accidents:  4
index:  195 ; vehicle:  Posta ; total accidents:  2
index:  196 ; vehicle:  ford ; total accidents:  4
index:  197 ; vehicle:  white ; total accidents:  3
index:  198 ; vehicle:  BOBCA ; total accidents:  8
index:  199 ; vehicle:  VAV ; total accidents:  2
index:  200 ; vehicle:  PICKU ; total accidents:  11
index:  201 ; vehicle:  truck ; total accidents:  36
index:  202 ; vehicle:  U HAU ; total accidents:  3
index:  203 ; vehicle:  LADDER 34 ; total accidents:  1
index:  204 ; vehicle:  5X8 T ; total accidents:  1
index:  205 ; vehicle:  mack ; total accidents:  3
index:  206 ; vehicle:  POSTA ; total accidents:  11
index:  207 ; vehicle:  comme ; total accidents:  9
index:  208 ; vehicle:  f15 ; total accidents:  1
index:  209 ; vehicle:  tower ; total accidents:  2
index:  210 ; vehicle:  const ; total accidents:  6
index:  211 ; vehicle:  WHITE ; total accidents:  6
index:  212 ; vehicle:  SPRIN ; total accidents:  7
index:  213 ; vehicle:  subur ; total accidents:  2
index:  214 ; vehicle:  Rescu ; total accidents:  3
index:  215 ; vehicle:  4DR ; total accidents:  2
index:  216 ; vehicle:  Ambu ; total accidents:  4
index:  217 ; vehicle:  FLATB ; total accidents:  9
index:  218 ; vehicle:  cater ; total accidents:  3
index:  219 ; vehicle:  tank ; total accidents:  3
index:  220 ; vehicle:  FRHT ; total accidents:  3
index:  221 ; vehicle:  Pick ; total accidents:  3
index:  222 ; vehicle:  TRuck ; total accidents:  1
index:  223 ; vehicle:  garba ; total accidents:  12
index:  224 ; vehicle:  MO PE ; total accidents:  1
index:  225 ; vehicle:  fire truck ; total accidents:  21
index:  226 ; vehicle:  HINO ; total accidents:  4
index:  227 ; vehicle:  dirtb ; total accidents:  1
index:  228 ; vehicle:  POIS ; total accidents:  1
index:  229 ; vehicle:  MTA C ; total accidents:  1
index:  230 ; vehicle:  CEMEN ; total accidents:  4
index:  231 ; vehicle:  semi- ; total accidents:  2
index:  232 ; vehicle:  G COM ; total accidents:  5
index:  233 ; vehicle:  cargo ; total accidents:  2
index:  234 ; vehicle:  unk ; total accidents:  31
index:  235 ; vehicle:  food ; total accidents:  2
index:  236 ; vehicle:  MINIV ; total accidents:  2
index:  237 ; vehicle:  PET ; total accidents:  1
index:  238 ; vehicle:  CONST ; total accidents:  9
index:  239 ; vehicle:  RESCU ; total accidents:  2
index:  240 ; vehicle:  picku ; total accidents:  5
index:  241 ; vehicle:  OMR ; total accidents:  10
index:  242 ; vehicle:  RINGO ; total accidents:  1
index:  243 ; vehicle:  Van Camper ; total accidents:  33
index:  244 ; vehicle:  1 ; total accidents:  2
index:  245 ; vehicle:  TRANS ; total accidents:  3
index:  246 ; vehicle:  BOOM ; total accidents:  4
index:  247 ; vehicle:  MOTOR ; total accidents:  29
index:  248 ; vehicle:  YW PO ; total accidents:  1
index:  249 ; vehicle:  Open Body ; total accidents:  73
index:  250 ; vehicle:  suv ; total accidents:  2
index:  251 ; vehicle:  us po ; total accidents:  2
index:  252 ; vehicle:  rmb ; total accidents:  1
index:  253 ; vehicle:  UHAUL ; total accidents:  13
index:  254 ; vehicle:  3 doo ; total accidents:  1
index:  255 ; vehicle:  forkl ; total accidents:  15
index:  256 ; vehicle:  GOLF ; total accidents:  6
index:  257 ; vehicle:  LIGHT ; total accidents:  4
index:  258 ; vehicle:  elect ; total accidents:  19
index:  259 ; vehicle:  APP ; total accidents:  1
index:  260 ; vehicle:  mail ; total accidents:  6
index:  261 ; vehicle:  MCY B ; total accidents:  1
index:  262 ; vehicle:  uhaul ; total accidents:  3
index:  263 ; vehicle:  CO ; total accidents:  4
index:  264 ; vehicle:  pick ; total accidents:  15
index:  265 ; vehicle:  GATOR ; total accidents:  5
index:  266 ; vehicle:  SELF ; total accidents:  15
index:  267 ; vehicle:  US PO ; total accidents:  9
index:  268 ; vehicle:  BACKH ; total accidents:  17
index:  269 ; vehicle:  freig ; total accidents:  2
index:  270 ; vehicle:  wagon ; total accidents:  4
index:  271 ; vehicle:  bobct ; total accidents:  1
index:  272 ; vehicle:  dirt ; total accidents:  1
index:  273 ; vehicle:  Hopper ; total accidents:  16
index:  274 ; vehicle:  mtr s ; total accidents:  1
index:  275 ; vehicle:  OZ MO ; total accidents:  1
index:  276 ; vehicle:  nycta ; total accidents:  1
index:  277 ; vehicle:  mta B ; total accidents:  1
index:  278 ; vehicle:  SUBUR ; total accidents:  6
index:  279 ; vehicle:  sanit ; total accidents:  12
index:  280 ; vehicle:  unkow ; total accidents:  1
index:  281 ; vehicle:  WINNE ; total accidents:  1
index:  282 ; vehicle:  KME/F ; total accidents:  1
index:  283 ; vehicle:  pedic ; total accidents:  1
index:  284 ; vehicle:  posta ; total accidents:  10
index:  285 ; vehicle:  VESPA ; total accidents:  2
index:  286 ; vehicle:  delv ; total accidents:  5
index:  287 ; vehicle:  REFRI ; total accidents:  2
index:  288 ; vehicle:  Truck ; total accidents:  21
index:  289 ; vehicle:  Tow T ; total accidents:  8
index:  290 ; vehicle:  BULLD ; total accidents:  10
index:  291 ; vehicle:  GLBEN ; total accidents:  4
index:  292 ; vehicle:  MTA B ; total accidents:  17
index:  293 ; vehicle:  scoot ; total accidents:  16
index:  294 ; vehicle:  oml ; total accidents:  2
index:  295 ; vehicle:  FLAT ; total accidents:  22
index:  296 ; vehicle:  TF ; total accidents:  1
index:  297 ; vehicle:  4 axe ; total accidents:  1
index:  298 ; vehicle:  MOVIN ; total accidents:  2
index:  299 ; vehicle:  SPC ; total accidents:  6
index:  300 ; vehicle:  U-HAU ; total accidents:  4
index:  301 ; vehicle:  DIRTB ; total accidents:  2
index:  302 ; vehicle:  EXCAV ; total accidents:  3
index:  303 ; vehicle:  12 PA ; total accidents:  1
index:  304 ; vehicle:  Stree ; total accidents:  3
index:  305 ; vehicle:  FDNY FIRE ; total accidents:  18
index:  306 ; vehicle:  WORK ; total accidents:  3
index:  307 ; vehicle:  nycha ; total accidents:  1
index:  308 ; vehicle:  Uhaul ; total accidents:  1
index:  309 ; vehicle:  box ; total accidents:  4
index:  310 ; vehicle:  del ; total accidents:  1

index:  311 ; vehicle:  NT TR ; total accidents:  1
index:  312 ; vehicle:  VERIZ ; total accidents:  1
index:  313 ; vehicle:  MTA U ; total accidents:  1
index:  314 ; vehicle:  FOOD ; total accidents:  5
index:  315 ; vehicle:  Glass Rack ; total accidents:  16
index:  316 ; vehicle:  ELEC. ; total accidents:  1
index:  317 ; vehicle:  Tram ; total accidents:  1
index:  318 ; vehicle:  CITY ; total accidents:  4
index:  319 ; vehicle:  tk ; total accidents:  7
index:  320 ; vehicle:  TL TR ; total accidents:  2
index:  321 ; vehicle:  east ; total accidents:  1
index:  322 ; vehicle:  Firet ; total accidents:  6
index:  323 ; vehicle:  Livery Bus ; total accidents:  1
index:  324 ; vehicle:  SD ; total accidents:  1
index:  325 ; vehicle:  TOWER ; total accidents:  4
index:  326 ; vehicle:  PRIVA ; total accidents:  1
index:  327 ; vehicle:  CABIN ; total accidents:  1
index:  328 ; vehicle:  Mo pa ; total accidents:  1
index:  329 ; vehicle:  ST150 ; total accidents:  1
index:  330 ; vehicle:  GE/SC ; total accidents:  1
index:  331 ; vehicle:  refg ; total accidents:  1
index:  332 ; vehicle:  small ; total accidents:  1
index:  333 ; vehicle:  Pavin ; total accidents:  1
index:  334 ; vehicle:  Crane ; total accidents:  4
index:  335 ; vehicle:  UT ; total accidents:  4
index:  336 ; vehicle:  E-BIK ; total accidents:  23
index:  337 ; vehicle:  White ; total accidents:  6
index:  338 ; vehicle:  omnib ; total accidents:  1
index:  339 ; vehicle:  NYC F ; total accidents:  2
index:  340 ; vehicle:  utili ; total accidents:  12
index:  341 ; vehicle:  Fork ; total accidents:  8
index:  342 ; vehicle:  RENTA ; total accidents:  1
index:  343 ; vehicle:  EMS ; total accidents:  6
index:  344 ; vehicle:  Tow t ; total accidents:  4
index:  345 ; vehicle:  Golf ; total accidents:  3
index:  346 ; vehicle:  omni ; total accidents:  1
index:  347 ; vehicle:  Minibike ; total accidents:  52
index:  348 ; vehicle:  UPS t ; total accidents:  1
index:  349 ; vehicle:  omr ; total accidents:  2
index:  350 ; vehicle:  1S ; total accidents:  1
index:  351 ; vehicle:  ABULA ; total accidents:  1
index:  352 ; vehicle:  dp ; total accidents:  2
index:  353 ; vehicle:  trk ; total accidents:  2
index:  354 ; vehicle:  LIVER ; total accidents:  2
index:  355 ; vehicle:  carri ; total accidents:  1
index:  356 ; vehicle:  P/SH ; total accidents:  10
index:  357 ; vehicle:  us postal ; total accidents:  1
index:  358 ; vehicle:  315 e ; total accidents:  1
index:  359 ; vehicle:  NEW Y ; total accidents:  3
index:  360 ; vehicle:  4whee ; total accidents:  1
index:  361 ; vehicle:  FREE ; total accidents:  1
index:  362 ; vehicle:  GRAY ; total accidents:  3
index:  363 ; vehicle:  Mecha ; total accidents:  1
index:  364 ; vehicle:  Sweep ; total accidents:  1
index:  365 ; vehicle:  Bucketload ; total accidents:  1
index:  366 ; vehicle:  LIMO ; total accidents:  176
index:  367 ; vehicle:  TRAC ; total accidents:  16
index:  368 ; vehicle:  SEMI- ; total accidents:  5
index:  369 ; vehicle:  3DC- ; total accidents:  1
index:  370 ; vehicle:  Tow ; total accidents:  4
index:  371 ; vehicle:  RD/S ; total accidents:  3
index:  372 ; vehicle:  STAK ; total accidents:  5
index:  373 ; vehicle:  HORSE ; total accidents:  2
index:  374 ; vehicle:  E ONE ; total accidents:  1
index:  375 ; vehicle:  work ; total accidents:  2
index:  376 ; vehicle:  mta b ; total accidents:  5
index:  377 ; vehicle:  FDNY TRUCK ; total accidents:  25
index:  378 ; vehicle:  Enclosed Body - Nonremovable Enclosure ; total accidents:  10
index:  379 ; vehicle:  Scoot ; total accidents:  19
index:  380 ; vehicle:  U.S. POSTA ; total accidents:  1
index:  381 ; vehicle:  SELF- ; total accidents:  1
index:  382 ; vehicle:  TRAILER ; total accidents:  57
index:  383 ; vehicle:  passa ; total accidents:  1
index:  384 ; vehicle:  HORSE CARR ; total accidents:  1
index:  385 ; vehicle:  nyc d ; total accidents:  1
index:  386 ; vehicle:  Mini ; total accidents:  3
index:  387 ; vehicle:  CARGO ; total accidents:  7
index:  388 ; vehicle:  VAN/T ; total accidents:  3
index:  389 ; vehicle:  OIL T ; total accidents:  3
index:  390 ; vehicle:  flat ; total accidents:  4
index:  391 ; vehicle:  VAN W ; total accidents:  1
index:  392 ; vehicle:  BS ; total accidents:  3
index:  393 ; vehicle:  C0MME ; total accidents:  1
index:  394 ; vehicle:  Farm Vehicle ; total accidents:  1
index:  395 ; vehicle:  USPS TRUCK ; total accidents:  15
index:  396 ; vehicle:  bobca ; total accidents:  6
index:  397 ; vehicle:  jeep ; total accidents:  1
index:  398 ; vehicle:  COMMM ; total accidents:  1
index:  399 ; vehicle:  NYPD ; total accidents:  3
index:  400 ; vehicle:  HIGHL ; total accidents:  1
index:  401 ; vehicle:  ELECTRIC B ; total accidents:  1
index:  402 ; vehicle:  EMS A ; total accidents:  3
index:  403 ; vehicle:  MAIL ; total accidents:  8
index:  404 ; vehicle:  G Sem ; total accidents:  1
index:  405 ; vehicle:  Marke ; total accidents:  1
index:  406 ; vehicle:  USPS MAIL ; total accidents:  3
index:  407 ; vehicle:  mopad ; total accidents:  1
index:  408 ; vehicle:  2 TON ; total accidents:  1
index:  409 ; vehicle:  bulld ; total accidents:  2
index:  410 ; vehicle:  Wagon ; total accidents:  3
index:  411 ; vehicle:  Inter ; total accidents:  1
index:  412 ; vehicle:  Cargo ; total accidents:  2
index:  413 ; vehicle:  NYC a ; total accidents:  1
index:  414 ; vehicle:  Sprin ; total accidents:  3
index:  415 ; vehicle:  15 Pa ; total accidents:  1
index:  416 ; vehicle:  City ; total accidents:  2
index:  417 ; vehicle:  PUMP ; total accidents:  1
index:  418 ; vehicle:  Pick- ; total accidents:  1
index:  419 ; vehicle:  Smart ; total accidents:  1
index:  420 ; vehicle:  mcy ; total accidents:  1
index:  421 ; vehicle:  MACK TRUCK ; total accidents:  1
index:  422 ; vehicle:  icecr ; total accidents:  1
index:  423 ; vehicle:  CMIX ; total accidents:  5
index:  424 ; vehicle:  CHART ; total accidents:  1
index:  425 ; vehicle:  boxtr ; total accidents:  1
index:  426 ; vehicle:  ice c ; total accidents:  1
index:  427 ; vehicle:  Food ; total accidents:  1
index:  428 ; vehicle:  Elect ; total accidents:  9
index:  429 ; vehicle:  trl ; total accidents:  2
index:  430 ; vehicle:  VAN/B ; total accidents:  1
index:  431 ; vehicle:  CART ; total accidents:  2
index:  432 ; vehicle:  spec ; total accidents:  1
index:  433 ; vehicle:  BK ; total accidents:  2
index:  434 ; vehicle:  Semi ; total accidents:  1
index:  435 ; vehicle:  seagr ; total accidents:  1
index:  436 ; vehicle:  e sco ; total accidents:  1
index:  437 ; vehicle:  WHEEL ; total accidents:  1
index:  438 ; vehicle:  UPS T ; total accidents:  1
index:  439 ; vehicle:  Subn ; total accidents:  6
index:  440 ; vehicle:  FORK- ; total accidents:  1
index:  441 ; vehicle:  Enclosed Body - Removable Enclosure ; total accidents:  8
index:  442 ; vehicle:  CASE ; total accidents:  2
index:  443 ; vehicle:  Work ; total accidents:  1
index:  444 ; vehicle:  R/V ; total accidents:  1
index:  445 ; vehicle:  HEAVY ; total accidents:  1
index:  446 ; vehicle:  fd tr ; total accidents:  1
index:  447 ; vehicle:  FD TR ; total accidents:  1
index:  448 ; vehicle:  Spc ; total accidents:  1
index:  449 ; vehicle:  rv ; total accidents:  2
index:  450 ; vehicle:  DUMPS ; total accidents:  3
index:  451 ; vehicle:  SWEEP ; total accidents:  3
index:  452 ; vehicle:  FD tr ; total accidents:  1
index:  453 ; vehicle:  E-MOT ; total accidents:  1
index:  454 ; vehicle:  FRONT ; total accidents:  1
index:  455 ; vehicle:  CAMP ; total accidents:  1
index:  456 ; vehicle:  NS AM ; total accidents:  1
index:  457 ; vehicle:  R/V C ; total accidents:  1
index:  458 ; vehicle:  PSD ; total accidents:  11
index:  459 ; vehicle:  SCOOTER ; total accidents:  24
index:  460 ; vehicle:  e-bik ; total accidents:  1
index:  461 ; vehicle:  POSTO ; total accidents:  1
index:  462 ; vehicle:  RGS ; total accidents:  1
index:  463 ; vehicle:  sgws ; total accidents:  1
index:  464 ; vehicle:  SWT ; total accidents:  3
index:  465 ; vehicle:  GOVER ; total accidents:  4
index:  466 ; vehicle:  Dumps ; total accidents:  1
index:  467 ; vehicle:  MINI ; total accidents:  3

index:  468 ; vehicle:  unknown ; total accidents:  11
index:  469 ; vehicle:  EBIKE ; total accidents:  6
index:  470 ; vehicle:  TRLR ; total accidents:  4
index:  471 ; vehicle:  2- to ; total accidents:  1
index:  472 ; vehicle:  BROOM ; total accidents:  1
index:  473 ; vehicle:  US POSTAL ; total accidents:  4
index:  474 ; vehicle:  Garba ; total accidents:  5
index:  475 ; vehicle:  CHERR ; total accidents:  1
index:  476 ; vehicle:  WORKH ; total accidents:  1
index:  477 ; vehicle:  Sanit ; total accidents:  9
index:  478 ; vehicle:  Tract ; total accidents:  8
index:  479 ; vehicle:  e com ; total accidents:  1
index:  480 ; vehicle:  BOAT ; total accidents:  2
index:  481 ; vehicle:  MARK ; total accidents:  1
index:  482 ; vehicle:  RMP ; total accidents:  4
index:  483 ; vehicle:  COUPE ; total accidents:  1
index:  484 ; vehicle:  EMRGN ; total accidents:  1
index:  485 ; vehicle:  E BIK ; total accidents:  7
index:  486 ; vehicle:  FIRE TRUCK ; total accidents:  104
index:  487 ; vehicle:  LIMOU ; total accidents:  3
index:  488 ; vehicle:  Fd fi ; total accidents:  1
index:  489 ; vehicle:  Comix ; total accidents:  1
index:  490 ; vehicle:  DUMPT ; total accidents:  2
index:  491 ; vehicle:  AMbul ; total accidents:  1
index:  492 ; vehicle:  trailer ; total accidents:  18
index:  493 ; vehicle:  Motor ; total accidents:  6
index:  494 ; vehicle:  12 Pa ; total accidents:  1
index:  495 ; vehicle:  Unkno ; total accidents:  11
index:  496 ; vehicle:  FED E ; total accidents:  3
index:  497 ; vehicle:  COURI ; total accidents:  4
index:  498 ; vehicle:  DIESE ; total accidents:  1
index:  499 ; vehicle:  Unkow ; total accidents:  1
index:  500 ; vehicle:  mc ; total accidents:  1
index:  501 ; vehicle:  USPOS ; total accidents:  2
index:  502 ; vehicle:  Grain ; total accidents:  3
index:  503 ; vehicle:  Bicyc ; total accidents:  1
index:  504 ; vehicle:  red t ; total accidents:  1
index:  505 ; vehicle:  Box t ; total accidents:  2
index:  506 ; vehicle:  comm ; total accidents:  3
index:  507 ; vehicle:  CMS-T ; total accidents:  1
index:  508 ; vehicle:  PASSE ; total accidents:  1
index:  509 ; vehicle:  USPS2 ; total accidents:  1
index:  510 ; vehicle:  NYC D ; total accidents:  1
index:  511 ; vehicle:  3 WHE ; total accidents:  2
index:  512 ; vehicle:  Log ; total accidents:  2
index:  513 ; vehicle:  NISSA ; total accidents:  1
index:  514 ; vehicle:  passe ; total accidents:  1
index:  515 ; vehicle:  Comme ; total accidents:  7
index:  516 ; vehicle:  MAC T ; total accidents:  1
index:  517 ; vehicle:  te ; total accidents:  1
index:  518 ; vehicle:  none ; total accidents:  1
index:  519 ; vehicle:  FIRETRUCK ; total accidents:  32
index:  520 ; vehicle:  Const ; total accidents:  1
index:  521 ; vehicle:  omm ; total accidents:  1
index:  522 ; vehicle:  TKTR ; total accidents:  1
index:  523 ; vehicle:  LTRL ; total accidents:  1
index:  524 ; vehicle:  US Po ; total accidents:  3
index:  525 ; vehicle:  U-Hau ; total accidents:  4
index:  526 ; vehicle:  COMER ; total accidents:  2
index:  527 ; vehicle:  SEA ; total accidents:  1
index:  528 ; vehicle:  VAN T ; total accidents:  11
index:  529 ; vehicle:  Mail ; total accidents:  1
index:  530 ; vehicle:  BUCKE ; total accidents:  1
index:  531 ; vehicle:  Snow ; total accidents:  1
index:  532 ; vehicle:  Hrse ; total accidents:  1
index:  533 ; vehicle:  NYCHA ; total accidents:  1
index:  534 ; vehicle:  Delv ; total accidents:  2
index:  535 ; vehicle:  moter ; total accidents:  1
index:  536 ; vehicle:  Picku ; total accidents:  2
index:  537 ; vehicle:  CAT P ; total accidents:  1
index:  538 ; vehicle:  SC ; total accidents:  2
index:  539 ; vehicle:  SEGWA ; total accidents:  1
index:  540 ; vehicle:  semi ; total accidents:  2
index:  541 ; vehicle:  TRACK EXCA ; total accidents:  1
index:  542 ; vehicle:  st ; total accidents:  1
index:  543 ; vehicle:  dumps ; total accidents:  2
index:  544 ; vehicle:  TIR ; total accidents:  1
index:  545 ; vehicle:  COMMU ; total accidents:  1
index:  546 ; vehicle:  movin ; total accidents:  1
index:  547 ; vehicle:  ï¿½MBU ; total accidents:  1
index:  548 ; vehicle:  NAVIG ; total accidents:  1
index:  549 ; vehicle:  nypd ; total accidents:  1
index:  550 ; vehicle:  Pas ; total accidents:  1
index:  551 ; vehicle:  Barri ; total accidents:  1
index:  552 ; vehicle:  MOPD ; total accidents:  4
index:  553 ; vehicle:  NTTRL ; total accidents:  1
index:  554 ; vehicle:  Acces ; total accidents:  2
index:  555 ; vehicle:  BTM ; total accidents:  1
index:  556 ; vehicle:  ACCES ; total accidents:  2
index:  557 ; vehicle:  E SCO ; total accidents:  4
index:  558 ; vehicle:  St ; total accidents:  2
index:  559 ; vehicle:  Van T ; total accidents:  1
index:  560 ; vehicle:  KUBOT ; total accidents:  1
index:  561 ; vehicle:  range ; total accidents:  1
index:  562 ; vehicle:  SKID- ; total accidents:  1
index:  563 ; vehicle:  ICE C ; total accidents:  3
index:  564 ; vehicle:  Mta ; total accidents:  1
index:  565 ; vehicle:  APPOR ; total accidents:  1
index:  566 ; vehicle:  DIRT ; total accidents:  2
index:  567 ; vehicle:  NYS A ; total accidents:  1
index:  568 ; vehicle:  E-Sco ; total accidents:  204
index:  569 ; vehicle:  TOWTR ; total accidents:  1
index:  570 ; vehicle:  PICK- ; total accidents:  2
index:  571 ; vehicle:  prks ; total accidents:  1
index:  572 ; vehicle:  CONT ; total accidents:  2
index:  573 ; vehicle:  g spc ; total accidents:  1
index:  574 ; vehicle:  POLIC ; total accidents:  1
index:  575 ; vehicle:  Parce ; total accidents:  1
index:  576 ; vehicle:  HI TA ; total accidents:  1
index:  577 ; vehicle:  35 FT ; total accidents:  1
index:  578 ; vehicle:  CAT. ; total accidents:  1
index:  579 ; vehicle:  PU ; total accidents:  1
index:  580 ; vehicle:  limo ; total accidents:  1
index:  581 ; vehicle:  USP M ; total accidents:  1
index:  582 ; vehicle:  SANTI ; total accidents:  1
index:  583 ; vehicle:  LIEBH ; total accidents:  1
index:  584 ; vehicle:  CAB ; total accidents:  2
index:  585 ; vehicle:  road ; total accidents:  1
index:  586 ; vehicle:  DOT T ; total accidents:  1
index:  587 ; vehicle:  FLAT/ ; total accidents:  1
index:  588 ; vehicle:  REP ; total accidents:  4
index:  589 ; vehicle:  PSH ; total accidents:  1
index:  590 ; vehicle:  DELVI ; total accidents:  1
index:  591 ; vehicle:  SKATE ; total accidents:  3
index:  592 ; vehicle:  ECONO ; total accidents:  2
index:  593 ; vehicle:  Amb ; total accidents:  5
index:  594 ; vehicle:  UHUAL ; total accidents:  2
index:  595 ; vehicle:  GRUMM ; total accidents:  1
index:  596 ; vehicle:  E-Scooter ; total accidents:  1726
index:  597 ; vehicle:  DEPT VAN # ; total accidents:  1
index:  598 ; vehicle:  E-Bike ; total accidents:  2643
index:  599 ; vehicle:  E450 ; total accidents:  1
index:  600 ; vehicle:  forklift ; total accidents:  9
index:  601 ; vehicle:  COMMERCIAL ; total accidents:  8
index:  602 ; vehicle:  YELLOWPOWE ; total accidents:  1
index:  603 ; vehicle:  DUMP TRUCK ; total accidents:  10
index:  604 ; vehicle:  LADDER TRU ; total accidents:  3
index:  605 ; vehicle:  197209 ; total accidents:  1
index:  606 ; vehicle:  amulance ; total accidents:  1
index:  607 ; vehicle:  Dump truck ; total accidents:  4
index:  608 ; vehicle:  GOLF CART ; total accidents:  3
index:  609 ; vehicle:  I-haul ; total accidents:  1
index:  610 ; vehicle:  MAIL TRUCK ; total accidents:  4
index:  611 ; vehicle:  RV/VAN ; total accidents:  1
index:  612 ; vehicle:  fdny truck ; total accidents:  2
index:  613 ; vehicle:  SCHOOL BUS ; total accidents:  11
index:  614 ; vehicle:  BOX TRUCK ; total accidents:  25
index:  615 ; vehicle:  FDNY EMS V ; total accidents:  1
index:  616 ; vehicle:  pay loader ; total accidents:  1
index:  617 ; vehicle:  pedicab ; total accidents:  1
index:  618 ; vehicle:  food truck ; total accidents:  1
index:  619 ; vehicle:  suburban ; total accidents:  2
index:  620 ; vehicle:  EMERGENCY ; total accidents:  1
index:  621 ; vehicle:  TRACTOR ; total accidents:  9
index:  622 ; vehicle:  tractor tr ; total accidents:  2
index:  623 ; vehicle:  TR-Trailer ; total accidents:  1
index:  624 ; vehicle:  ESU RESCUE ; total accidents:  1

index:  625 ; vehicle:  D/V WB ; total accidents:  1
index:  626 ; vehicle:  Bobcat ; total accidents:  1
index:  627 ; vehicle:  SE ; total accidents:  2
index:  628 ; vehicle:  nat grid t ; total accidents:  1
index:  629 ; vehicle:  UTILITY TR ; total accidents:  4
index:  630 ; vehicle:  MTA ; total accidents:  2
index:  631 ; vehicle:  postal ser ; total accidents:  1
index:  632 ; vehicle:  FORK LIFT ; total accidents:  7
index:  633 ; vehicle:  Unknown ; total accidents:  24
index:  634 ; vehicle:  Delivery ; total accidents:  6
index:  635 ; vehicle:  G com ; total accidents:  1
index:  636 ; vehicle:  TOW TRUCK ; total accidents:  22
index:  637 ; vehicle:  PICKUP TRU ; total accidents:  5
index:  638 ; vehicle:  School bus ; total accidents:  3
index:  639 ; vehicle:  ambulance ; total accidents:  45
index:  640 ; vehicle:  PUSH SCOOT ; total accidents:  1
index:  641 ; vehicle:  SELF INSUR ; total accidents:  5
index:  642 ; vehicle:  FREIGHTLIN ; total accidents:  2
index:  643 ; vehicle:  FDNY FIRET ; total accidents:  3
index:  644 ; vehicle:  Hearse ; total accidents:  1
index:  645 ; vehicle:  delviery ; total accidents:  1
index:  646 ; vehicle:  USPS #7530 ; total accidents:  1
index:  647 ; vehicle:  Horse Trai ; total accidents:  1
index:  648 ; vehicle:  ford econo ; total accidents:  1
index:  649 ; vehicle:  Firetruck ; total accidents:  6
index:  650 ; vehicle:  FDNY LADDE ; total accidents:  4
index:  651 ; vehicle:  Trailer ; total accidents:  23
index:  652 ; vehicle:  dump truck ; total accidents:  3
index:  653 ; vehicle:  escavator ; total accidents:  1
index:  654 ; vehicle:  USPS POSTA ; total accidents:  1
index:  655 ; vehicle:  White ambu ; total accidents:  1
index:  656 ; vehicle:  FREIGHT TR ; total accidents:  1
index:  657 ; vehicle:  pc ; total accidents:  2
index:  658 ; vehicle:  POSTAL TRU ; total accidents:  4
index:  659 ; vehicle:  Commercial ; total accidents:  3
index:  660 ; vehicle:  Fdny ambul ; total accidents:  2
index:  661 ; vehicle:  Work van ; total accidents:  1
index:  662 ; vehicle:  MOTOR SCOO ; total accidents:  6
index:  663 ; vehicle:  E bike ; total accidents:  1
index:  664 ; vehicle:  PICK UP TR ; total accidents:  5
index:  665 ; vehicle:  government ; total accidents:  1
index:  666 ; vehicle:  Ford sprin ; total accidents:  1
index:  667 ; vehicle:  postal tru ; total accidents:  4
index:  668 ; vehicle:  FLATBED ; total accidents:  3
index:  669 ; vehicle:  E-BIKE ; total accidents:  11
index:  670 ; vehicle:  BACK HOE ; total accidents:  2
index:  671 ; vehicle:  UNKNOWN ; total accidents:  42
index:  672 ; vehicle:  0 ; total accidents:  4
index:  673 ; vehicle:  Fire Truck ; total accidents:  17
index:  674 ; vehicle:  CHEVROLET ; total accidents:  1
index:  675 ; vehicle:  E-bike ; total accidents:  3
index:  676 ; vehicle:  FDNY Fire ; total accidents:  4
index:  677 ; vehicle:  CARGO VAN ; total accidents:  2
index:  678 ; vehicle:  tow truck ; total accidents:  3
index:  679 ; vehicle:  LIGHT TRAI ; total accidents:  2
index:  680 ; vehicle:  FUSION ; total accidents:  1
index:  681 ; vehicle:  Pick up ; total accidents:  6
index:  682 ; vehicle:  NYC FD ; total accidents:  1
index:  683 ; vehicle:  NYC AMBULA ; total accidents:  2
index:  684 ; vehicle:  postal bus ; total accidents:  1
index:  685 ; vehicle:  FDNY Ambul ; total accidents:  6
index:  686 ; vehicle:  FIRE ENGIN ; total accidents:  3
index:  687 ; vehicle:  DELIVERY T ; total accidents:  7
index:  688 ; vehicle:  ELEC. UNIC ; total accidents:  1
index:  689 ; vehicle:  Pick up Tr ; total accidents:  1
index:  690 ; vehicle:  CAT ; total accidents:  5
index:  691 ; vehicle:  ELECTRIC S ; total accidents:  2
index:  692 ; vehicle:  FDNY Engin ; total accidents:  1
index:  693 ; vehicle:  BOBCAT FOR ; total accidents:  1
index:  694 ; vehicle:  E REVEL SC ; total accidents:  1
index:  695 ; vehicle:  Fork lift ; total accidents:  4
index:  696 ; vehicle:  Horse ; total accidents:  1
index:  697 ; vehicle:  SLINGSHOT ; total accidents:  1
index:  698 ; vehicle:  commercial ; total accidents:  3
index:  699 ; vehicle:  Wh Ford co ; total accidents:  1
index:  700 ; vehicle:  FDNY AMBUL ; total accidents:  15
index:  701 ; vehicle:  ROAD SWEEP ; total accidents:  2
index:  702 ; vehicle:  DOT EQUIPM ; total accidents:  1
index:  703 ; vehicle:  Bucket Tru ; total accidents:  1
index:  704 ; vehicle:  UTILITY VE ; total accidents:  4
index:  705 ; vehicle:  UNKN ; total accidents:  1
index:  706 ; vehicle:  backhoe ; total accidents:  1
index:  707 ; vehicle:  Tractor ; total accidents:  1
index:  708 ; vehicle:  MOVING VAN ; total accidents:  1
index:  709 ; vehicle:  AMBULENCE ; total accidents:  4
index:  710 ; vehicle:  18 WHEELER ; total accidents:  1
index:  711 ; vehicle:  GARBAGE TR ; total accidents:  8
index:  712 ; vehicle:  FDNY #226 ; total accidents:  1
index:  713 ; vehicle:  Go kart ; total accidents:  2
index:  714 ; vehicle:  MOTORSCOOT ; total accidents:  2
index:  715 ; vehicle:  cross ; total accidents:  1
index:  716 ; vehicle:  JOHN DEERE ; total accidents:  2
index:  717 ; vehicle:  Front-Load ; total accidents:  1
index:  718 ; vehicle:  Pumper ; total accidents:  1
index:  719 ; vehicle:  GEN  AMBUL ; total accidents:  1
index:  720 ; vehicle:  DELIVERY ; total accidents:  6
index:  721 ; vehicle:  dilevery t ; total accidents:  1
index:  722 ; vehicle:  DRILL RIG ; total accidents:  1
index:  723 ; vehicle:  FDNY fire ; total accidents:  2
index:  724 ; vehicle:  TRUCK VAN ; total accidents:  1
index:  725 ; vehicle:  Pick up tr ; total accidents:  4
index:  726 ; vehicle:  SKATEBOARD ; total accidents:  4
index:  727 ; vehicle:  ford van ; total accidents:  1
index:  728 ; vehicle:  Fire truck ; total accidents:  17
index:  729 ; vehicle:  scooter ; total accidents:  14
index:  730 ; vehicle:  AMBULACE ; total accidents:  2
index:  731 ; vehicle:  forlift ; total accidents:  1
index:  732 ; vehicle:  fdny ems ; total accidents:  1
index:  733 ; vehicle:  box truck ; total accidents:  6
index:  734 ; vehicle:  Fork Lift ; total accidents:  2
index:  735 ; vehicle:  FORKLIFT ; total accidents:  16
index:  736 ; vehicle:  USPS/GOVT ; total accidents:  1
index:  737 ; vehicle:  SMART CAR ; total accidents:  1
index:  738 ; vehicle:  Can ; total accidents:  1
index:  739 ; vehicle:  PICK UP ; total accidents:  6
index:  740 ; vehicle:  FLATBED FR ; total accidents:  1
index:  741 ; vehicle:  utility ; total accidents:  2
index:  742 ; vehicle:  E-UNICYCLE ; total accidents:  1
index:  743 ; vehicle:  Cement Tru ; total accidents:  2
index:  744 ; vehicle:  FIRTRUCK ; total accidents:  1
index:  745 ; vehicle:  Courier ; total accidents:  2
index:  746 ; vehicle:  POWER SHOV ; total accidents:  7
index:  747 ; vehicle:  F550 ; total accidents:  2
index:  748 ; vehicle:  Fire Engin ; total accidents:  4
index:  749 ; vehicle:  Street Swe ; total accidents:  1
index:  750 ; vehicle:  Scooter ; total accidents:  25
index:  751 ; vehicle:  Street Cle ; total accidents:  1
index:  752 ; vehicle:  firetruck ; total accidents:  7
index:  753 ; vehicle:  TTAILER ; total accidents:  1
index:  754 ; vehicle:  BICYCLE ; total accidents:  1
index:  755 ; vehicle:  CATAPILLAR ; total accidents:  1
index:  756 ; vehicle:  E-scooter ; total accidents:  8
index:  757 ; vehicle:  FLAT  BED ; total accidents:  1
index:  758 ; vehicle:  UTILITY ; total accidents:  2
index:  759 ; vehicle:  postal van ; total accidents:  1
index:  760 ; vehicle:  ebike ; total accidents:  2
index:  761 ; vehicle:  PERM ; total accidents:  1
index:  762 ; vehicle:  FDNY EMS ; total accidents:  4
index:  763 ; vehicle:  Van truck ; total accidents:  1
index:  764 ; vehicle:  Sanitation ; total accidents:  4
index:  765 ; vehicle:  Com ; total accidents:  2
index:  766 ; vehicle:  VAN TRUCK ; total accidents:  2
index:  767 ; vehicle:  USPS truck ; total accidents:  2
index:  768 ; vehicle:  na ; total accidents:  2
index:  769 ; vehicle:  pick up ; total accidents:  1
index:  770 ; vehicle:  U HAUL TRU ; total accidents:  1
index:  771 ; vehicle:  Subr ; total accidents:  1
index:  772 ; vehicle:  FDNY ENGIN ; total accidents:  5

index:  773 ; vehicle:  PICKUP ; total accidents:  4
index:  774 ; vehicle:  EMS Ambula ; total accidents:  1
index:  775 ; vehicle:  fdny ambul ; total accidents:  1
index:  776 ; vehicle:  nyc EMS ; total accidents:  1
index:  777 ; vehicle:  sanitaton ; total accidents:  1
index:  778 ; vehicle:  Government ; total accidents:  1
index:  779 ; vehicle:  UTILITY WH ; total accidents:  1
index:  780 ; vehicle:  Ambulette ; total accidents:  1
index:  781 ; vehicle:  Fedex ; total accidents:  1
index:  782 ; vehicle:  G AMB ; total accidents:  3
index:  783 ; vehicle:  USPS Truck ; total accidents:  1
index:  784 ; vehicle:  Box truck ; total accidents:  6
index:  785 ; vehicle:  Sprinter v ; total accidents:  1
index:  786 ; vehicle:  MARKED VAN ; total accidents:  1
index:  787 ; vehicle:  SKYWATCH ; total accidents:  1
index:  788 ; vehicle:  VAN/TRUCK ; total accidents:  3
index:  789 ; vehicle:  Ram Promas ; total accidents:  1
index:  790 ; vehicle:  SKID LOADE ; total accidents:  1
index:  791 ; vehicle:  Power Shov ; total accidents:  1
index:  792 ; vehicle:  sedan ; total accidents:  2
index:  793 ; vehicle:  G PSD ; total accidents:  2
index:  794 ; vehicle:  Unk ; total accidents:  10
index:  795 ; vehicle:  SPECIAL CO ; total accidents:  1
index:  796 ; vehicle:  Quality tr ; total accidents:  1
index:  797 ; vehicle:  SUBURBAN ; total accidents:  2
index:  798 ; vehicle:  SANITATION ; total accidents:  6
index:  799 ; vehicle:  Horse carr ; total accidents:  1
index:  800 ; vehicle:  Forklift ; total accidents:  9
index:  801 ; vehicle:  SNOW PLOW ; total accidents:  1
index:  802 ; vehicle:  sanitaion ; total accidents:  1
index:  803 ; vehicle:  Excavator ; total accidents:  2
index:  804 ; vehicle:  FORD VAN ; total accidents:  1
index:  805 ; vehicle:  Postal tru ; total accidents:  2
index:  806 ; vehicle:  BULLDOZER ; total accidents:  1
index:  807 ; vehicle:  con ed tru ; total accidents:  1
index:  808 ; vehicle:  CMIXER ; total accidents:  1
index:  809 ; vehicle:  UPS TRUCK ; total accidents:  2
index:  810 ; vehicle:  POWER LADD ; total accidents:  1
index:  811 ; vehicle:  SUBN - AMB ; total accidents:  1
index:  812 ; vehicle:  Backhoe Lo ; total accidents:  1
index:  813 ; vehicle:  Motorscoot ; total accidents:  2
index:  814 ; vehicle:  Mercedes ; total accidents:  1
index:  815 ; vehicle:  PASSENGER ; total accidents:  2
index:  816 ; vehicle:  post offic ; total accidents:  1
index:  817 ; vehicle:  pickup ; total accidents:  4
index:  818 ; vehicle:  POSTAL VEH ; total accidents:  3
index:  819 ; vehicle:  MTA bus ; total accidents:  1
index:  820 ; vehicle:  utility tr ; total accidents:  2
index:  821 ; vehicle:  OML/OMNIBU ; total accidents:  1
index:  822 ; vehicle:  FORD SPRIN ; total accidents:  1
index:  823 ; vehicle:  TRAILER/FL ; total accidents:  1
index:  824 ; vehicle:  DIRT BIKE ; total accidents:  9
index:  825 ; vehicle:  TRAILEE ; total accidents:  1
index:  826 ; vehicle:  SPARK150 S ; total accidents:  1
index:  827 ; vehicle:  HERTZ RAM ; total accidents:  1
index:  828 ; vehicle:  MTA Bus ; total accidents:  1
index:  829 ; vehicle:  CATER ; total accidents:  6
index:  830 ; vehicle:  SEMI TRAIL ; total accidents:  2
index:  831 ; vehicle:  AMBULANE ; total accidents:  2
index:  832 ; vehicle:  NYPD VAN ; total accidents:  1
index:  833 ; vehicle:  EMS bus ; total accidents:  1
index:  834 ; vehicle:  NYS Ambula ; total accidents:  1
index:  835 ; vehicle:  SANMEN COU ; total accidents:  1
index:  836 ; vehicle:  SHUTTLE BU ; total accidents:  1
index:  837 ; vehicle:  UHAL ; total accidents:  1
index:  838 ; vehicle:  Dodge ; total accidents:  1
index:  839 ; vehicle:  kick scoot ; total accidents:  1
index:  840 ; vehicle:  Mini Van ; total accidents:  1
index:  841 ; vehicle:  MTA BUS ; total accidents:  4
index:  842 ; vehicle:  TRUCK COMM ; total accidents:  1
index:  843 ; vehicle:  Ford Van ; total accidents:  1
index:  844 ; vehicle:  Dirt Bike ; total accidents:  2
index:  845 ; vehicle:  Skywatch ; total accidents:  1
index:  846 ; vehicle:  TL ; total accidents:  3
index:  847 ; vehicle:  Dent and S ; total accidents:  1
index:  848 ; vehicle:  MOTOR HOME ; total accidents:  2
index:  849 ; vehicle:  mini van ; total accidents:  1
index:  850 ; vehicle:  usps truck ; total accidents:  1
index:  851 ; vehicle:  Grumman LL ; total accidents:  1
index:  852 ; vehicle:  994 ; total accidents:  2
index:  853 ; vehicle:  gas scoote ; total accidents:  1
index:  854 ; vehicle:  Pick wh ; total accidents:  1
index:  855 ; vehicle:  NYC SANITA ; total accidents:  1
index:  856 ; vehicle:  DEPARTMENT ; total accidents:  1
index:  857 ; vehicle:  NYS AMBULA ; total accidents:  2
index:  858 ; vehicle:  DODGE RAM ; total accidents:  1
index:  859 ; vehicle:  BOX ; total accidents:  3
index:  860 ; vehicle:  Gas scoote ; total accidents:  1
index:  861 ; vehicle:  HWH ; total accidents:  1
index:  862 ; vehicle:  Unmarked V ; total accidents:  1
index:  863 ; vehicle:  CHERV ; total accidents:  1
index:  864 ; vehicle:  Post offic ; total accidents:  1
index:  865 ; vehicle:  MINI BUS ; total accidents:  1
index:  866 ; vehicle:  MOVING TRU ; total accidents:  1
index:  867 ; vehicle:  Mopd ; total accidents:  1
index:  868 ; vehicle:  Yamaha ; total accidents:  1
index:  869 ; vehicle:  commerical ; total accidents:  1
index:  870 ; vehicle:  SEDONA ; total accidents:  1
index:  871 ; vehicle:  UTILITY VA ; total accidents:  2
index:  872 ; vehicle:  GAS POWERE ; total accidents:  1
index:  873 ; vehicle:  ENGINE SP0 ; total accidents:  1
index:  874 ; vehicle:  Pass ; total accidents:  1
index:  875 ; vehicle:  US Mail Tr ; total accidents:  1
index:  876 ; vehicle:  gas mo ped ; total accidents:  1
index:  877 ; vehicle:  SCOOTER GA ; total accidents:  1
index:  878 ; vehicle:  FDNY Firet ; total accidents:  2
index:  879 ; vehicle:  Pro master ; total accidents:  1
index:  880 ; vehicle:  WORK VAN ; total accidents:  2
index:  881 ; vehicle:  E scooter ; total accidents:  1
index:  882 ; vehicle:  50cc Scoot ; total accidents:  1
index:  883 ; vehicle:  Cement tru ; total accidents:  1
index:  884 ; vehicle:  VMS ; total accidents:  2
index:  885 ; vehicle:  Constructi ; total accidents:  1
index:  886 ; vehicle:  Mack ; total accidents:  1
index:  887 ; vehicle:  police rep ; total accidents:  1
index:  888 ; vehicle:  TLR ; total accidents:  1
index:  889 ; vehicle:  SCHOOL  BU ; total accidents:  1
index:  890 ; vehicle:  NonMotordS ; total accidents:  1
index:  891 ; vehicle:  FDNY Truck ; total accidents:  3
index:  892 ; vehicle:  EC3 ; total accidents:  1
index:  893 ; vehicle:  crane boom ; total accidents:  1
index:  894 ; vehicle:  work truck ; total accidents:  1
index:  895 ; vehicle:  Mack Truck ; total accidents:  1
index:  896 ; vehicle:  ECONOLINE ; total accidents:  2
index:  897 ; vehicle:  UPS ; total accidents:  2
index:  898 ; vehicle:  VAN WH ; total accidents:  1
index:  899 ; vehicle:  BOOM LIFT ; total accidents:  2
index:  900 ; vehicle:  U-Haul min ; total accidents:  1
index:  901 ; vehicle:  Pickup tru ; total accidents:  2
index:  902 ; vehicle:  freight ; total accidents:  1
index:  903 ; vehicle:  12 PASSENG ; total accidents:  1
index:  904 ; vehicle:  STREET SWE ; total accidents:  2
index:  905 ; vehicle:  LOCOMOTIVE ; total accidents:  1
index:  906 ; vehicle:  12 passage ; total accidents:  1
index:  907 ; vehicle:  PUMPER ; total accidents:  2
index:  908 ; vehicle:  STREET CLE ; total accidents:  1
index:  909 ; vehicle:  SBN ; total accidents:  1
index:  910 ; vehicle:  METAL ; total accidents:  1
index:  911 ; vehicle:  track ; total accidents:  2
index:  912 ; vehicle:  rolle ; total accidents:  1
index:  913 ; vehicle:  F350 ; total accidents:  1
index:  914 ; vehicle:  UNKOW ; total accidents:  3
index:  915 ; vehicle:  PISH ; total accidents:  1
index:  916 ; vehicle:  navig ; total accidents:  1
index:  917 ; vehicle:  taxi ; total accidents:  3
index:  918 ; vehicle:  VMS SIGN ; total accidents:  1
index:  919 ; vehicle:  trc ; total accidents:  1
index:  920 ; vehicle:  12 fe ; total accidents:  1
index:  921 ; vehicle:  M/A ; total accidents:  1

index:  922 ; vehicle:  OFF R ; total accidents:  1
index:  923 ; vehicle:  PAS V ; total accidents:  1
index:  924 ; vehicle:  Snowmobile ; total accidents:  3
index:  925 ; vehicle:  POST ; total accidents:  1
index:  926 ; vehicle:  HEIL ; total accidents:  1
index:  927 ; vehicle:  tt ; total accidents:  1
index:  928 ; vehicle:  NOT I ; total accidents:  1
index:  929 ; vehicle:  FIre ; total accidents:  1
index:  930 ; vehicle:  COM/A ; total accidents:  1
index:  931 ; vehicle:  utilt ; total accidents:  1
index:  932 ; vehicle:  NYC f ; total accidents:  1
index:  933 ; vehicle:  LEFT ; total accidents:  1
index:  934 ; vehicle:  DLVR ; total accidents:  1
index:  935 ; vehicle:  mta ; total accidents:  1
index:  936 ; vehicle:  JEEP ; total accidents:  1
index:  937 ; vehicle:  JOHN ; total accidents:  2
index:  938 ; vehicle:  WESCO ; total accidents:  1
index:  939 ; vehicle:  NAA ; total accidents:  1
index:  940 ; vehicle:  snow ; total accidents:  1
index:  941 ; vehicle:  WASTE ; total accidents:  2
index:  942 ; vehicle:  Ford ; total accidents:  1
index:  943 ; vehicle:  Back ; total accidents:  1
index:  944 ; vehicle:  foor ; total accidents:  1
index:  945 ; vehicle:  UK ; total accidents:  1
index:  946 ; vehicle:  PZ ; total accidents:  2
index:  947 ; vehicle:  Mp ; total accidents:  1
index:  948 ; vehicle:  Tank ; total accidents:  1
index:  949 ; vehicle:  COM T ; total accidents:  2
index:  950 ; vehicle:  push ; total accidents:  1
index:  951 ; vehicle:  E250 ; total accidents:  1
index:  952 ; vehicle:  INTL ; total accidents:  1
index:  953 ; vehicle:  TUCK ; total accidents:  1
index:  954 ; vehicle:  electric s ; total accidents:  2
index:  955 ; vehicle:  SEN ; total accidents:  1
index:  956 ; vehicle:  INTER ; total accidents:  2
index:  957 ; vehicle:  Carri ; total accidents:  2
index:  958 ; vehicle:  big r ; total accidents:  1
index:  959 ; vehicle:  speac ; total accidents:  1
index:  960 ; vehicle:  llv ; total accidents:  1
index:  961 ; vehicle:  STERL ; total accidents:  1
index:  962 ; vehicle:  Broom ; total accidents:  1
index:  963 ; vehicle:  excav ; total accidents:  3
index:  964 ; vehicle:  UNKWN ; total accidents:  1
index:  965 ; vehicle:  stak ; total accidents:  2
index:  966 ; vehicle:  ACCEE ; total accidents:  1
index:  967 ; vehicle:  G PAS ; total accidents:  1
index:  968 ; vehicle:  DLEV ; total accidents:  1
index:  969 ; vehicle:  000 ; total accidents:  1
index:  970 ; vehicle:  PLOW ; total accidents:  2
index:  971 ; vehicle:  JUNST ; total accidents:  1
index:  972 ; vehicle:  mac 1 ; total accidents:  1
index:  973 ; vehicle:  GENIE ; total accidents:  1
index:  974 ; vehicle:  crane ; total accidents:  2
index:  975 ; vehicle:  DEP V ; total accidents:  1
index:  976 ; vehicle:  E COM ; total accidents:  2
index:  977 ; vehicle:  acces ; total accidents:  2
index:  978 ; vehicle:  wesco ; total accidents:  1
index:  979 ; vehicle:  flatb ; total accidents:  1
index:  980 ; vehicle:  EXPRE ; total accidents:  1
index:  981 ; vehicle:  DRONE ; total accidents:  1
index:  982 ; vehicle:  NYC S ; total accidents:  1
index:  983 ; vehicle:  E-bik ; total accidents:  3
index:  984 ; vehicle:  All-Terrain Vehicle ; total accidents:  1
index:  985 ; vehicle:  UNK T ; total accidents:  1
index:  986 ; vehicle:  U.S.P ; total accidents:  1
index:  987 ; vehicle:  horse ; total accidents:  4
index:  988 ; vehicle:  nyc s ; total accidents:  1
index:  989 ; vehicle:  PETER ; total accidents:  1
index:  990 ; vehicle:  uliti ; total accidents:  1
index:  991 ; vehicle:  yello ; total accidents:  2
index:  992 ; vehicle:  TR/C ; total accidents:  1
index:  993 ; vehicle:  HOUSE ; total accidents:  1
index:  994 ; vehicle:  back ; total accidents:  2
index:  995 ; vehicle:  None ; total accidents:  1
index:  996 ; vehicle:  hino ; total accidents:  1
index:  997 ; vehicle:  clean ; total accidents:  1
index:  998 ; vehicle:  Light Towe ; total accidents:  1
index:  999 ; vehicle:  YLL P ; total accidents:  1
index:  1000 ; vehicle:  LIFT ; total accidents:  1
index:  1001 ; vehicle:  WANC ; total accidents:  1
index:  1002 ; vehicle:  ELEC ; total accidents:  1
index:  1003 ; vehicle:  Freig ; total accidents:  2
index:  1004 ; vehicle:  ES ; total accidents:  1
index:  1005 ; vehicle:  BUSS ; total accidents:  1
index:  1006 ; vehicle:  FDny ; total accidents:  1
index:  1007 ; vehicle:  AP ; total accidents:  1
index:  1008 ; vehicle:  BUS M ; total accidents:  1
index:  1009 ; vehicle:  FORTL ; total accidents:  1
index:  1010 ; vehicle:  Util ; total accidents:  1
index:  1011 ; vehicle:  TRLPM ; total accidents:  1
index:  1012 ; vehicle:  light ; total accidents:  1
index:  1013 ; vehicle:  DELV. ; total accidents:  1
index:  1014 ; vehicle:  red, ; total accidents:  1
index:  1015 ; vehicle:  IP ; total accidents:  1
index:  1016 ; vehicle:  utlit ; total accidents:  1
index:  1017 ; vehicle:  Humme ; total accidents:  1
index:  1018 ; vehicle:  UD ; total accidents:  1
index:  1019 ; vehicle:  scaff ; total accidents:  1
index:  1020 ; vehicle:  armor ; total accidents:  2
index:  1021 ; vehicle:  nissa ; total accidents:  1
index:  1022 ; vehicle:  DUMPSTER ; total accidents:  1
index:  1023 ; vehicle:  pick- ; total accidents:  1
index:  1024 ; vehicle:  013 ; total accidents:  1
index:  1025 ; vehicle:  ENGIN ; total accidents:  2
index:  1026 ; vehicle:  MAN L ; total accidents:  2
index:  1027 ; vehicle:  E PAS ; total accidents:  1
index:  1028 ; vehicle:  VANT ; total accidents:  1
index:  1029 ; vehicle:  CAMPE ; total accidents:  1
index:  1030 ; vehicle:  BOOML ; total accidents:  1
index:  1031 ; vehicle:  JCB40 ; total accidents:  1
index:  1032 ; vehicle:  GMC V ; total accidents:  1
index:  1033 ; vehicle:  frieg ; total accidents:  2
index:  1034 ; vehicle:  Passe ; total accidents:  1
index:  1035 ; vehicle:  00 ; total accidents:  1
index:  1036 ; vehicle:  UNKNOW ; total accidents:  2
index:  1037 ; vehicle:  TRIAL ; total accidents:  1
index:  1038 ; vehicle:  JLG B ; total accidents:  1
index:  1039 ; vehicle:  dsny ; total accidents:  2
index:  1040 ; vehicle:  Tlr ; total accidents:  1
index:  1041 ; vehicle:  SEMI-TRAIL ; total accidents:  1
index:  1042 ; vehicle:  Limou ; total accidents:  1
index:  1043 ; vehicle:  cat 3 ; total accidents:  1
index:  1044 ; vehicle:  RYDER ; total accidents:  1
index:  1045 ; vehicle:  ambulette ; total accidents:  1
index:  1046 ; vehicle:  HI-LO ; total accidents:  1
index:  1047 ; vehicle:  TRAILOR ; total accidents:  3
index:  1048 ; vehicle:  nyc a ; total accidents:  1
index:  1049 ; vehicle:  HWY C ; total accidents:  1
index:  1050 ; vehicle:  MINIVAN ; total accidents:  1
index:  1051 ; vehicle:  2 DOO ; total accidents:  1
index:  1052 ; vehicle:  Fdny ; total accidents:  2
index:  1053 ; vehicle:  Unk, ; total accidents:  1
index:  1054 ; vehicle:  Unkn ; total accidents:  1
index:  1055 ; vehicle:  Veh L ; total accidents:  1
index:  1056 ; vehicle:  BOB C ; total accidents:  2
index:  1057 ; vehicle:  trash ; total accidents:  1
index:  1058 ; vehicle:  spc p ; total accidents:  1
index:  1059 ; vehicle:  GAS S ; total accidents:  1
index:  1060 ; vehicle:  FD LA ; total accidents:  1
index:  1061 ; vehicle:  Us po ; total accidents:  1
index:  1062 ; vehicle:  B5-44 ; total accidents:  1
index:  1063 ; vehicle:  Com t ; total accidents:  1
index:  1064 ; vehicle:  Uber ; total accidents:  1
index:  1065 ; vehicle:  mot s ; total accidents:  1
index:  1066 ; vehicle:  LP ; total accidents:  1
index:  1067 ; vehicle:  (ceme ; total accidents:  1
index:  1068 ; vehicle:  Chevr ; total accidents:  1
index:  1069 ; vehicle:  f550 ; total accidents:  1
index:  1070 ; vehicle:  HOTDO ; total accidents:  1
index:  1071 ; vehicle:  WC ; total accidents:  1
index:  1072 ; vehicle:  Lift ; total accidents:  2
index:  1073 ; vehicle:  UKN ; total accidents:  2
index:  1074 ; vehicle:  UTLL ; total accidents:  1
index:  1075 ; vehicle:  SMART ; total accidents:  1
index:  1076 ; vehicle:  COM. ; total accidents:  1
index:  1077 ; vehicle:  Porta ; total accidents:  1
index:  1078 ; vehicle:  Hand ; total accidents:  1

index:  1079 ; vehicle:  e bik ; total accidents:  1
index:  1080 ; vehicle:  OBJEC ; total accidents:  1
index:  1081 ; vehicle:  MILLI ; total accidents:  1
index:  1082 ; vehicle:  Boom ; total accidents:  1
index:  1083 ; vehicle:  EMS H ; total accidents:  1
index:  1084 ; vehicle:  ND ; total accidents:  1
index:  1085 ; vehicle:  SUBN/ ; total accidents:  1
index:  1086 ; vehicle:  DUNBA ; total accidents:  1
index:  1087 ; vehicle:  TRANSIT VA ; total accidents:  1
index:  1088 ; vehicle:  PEDIC ; total accidents:  1
index:  1089 ; vehicle:  nyc f ; total accidents:  1
index:  1090 ; vehicle:  Electronic ; total accidents:  1
index:  1091 ; vehicle:  anbul ; total accidents:  1
index:  1092 ; vehicle:  MOPET ; total accidents:  2
index:  1093 ; vehicle:  oil t ; total accidents:  1
index:  1094 ; vehicle:  mecha ; total accidents:  1
index:  1095 ; vehicle:  GOV'T ; total accidents:  1
index:  1096 ; vehicle:  delivery t ; total accidents:  3
index:  1097 ; vehicle:  DIG-I ; total accidents:  1
index:  1098 ; vehicle:  FRE T ; total accidents:  1
index:  1099 ; vehicle:  JohnD ; total accidents:  1
index:  1100 ; vehicle:  Trac ; total accidents:  1
index:  1101 ; vehicle:  Cater ; total accidents:  1
index:  1102 ; vehicle:  E ; total accidents:  1
index:  1103 ; vehicle:  OML/ ; total accidents:  1
index:  1104 ; vehicle:  PCH ; total accidents:  1
index:  1105 ; vehicle:  E350 ; total accidents:  1
index:  1106 ; vehicle:  UNNKO ; total accidents:  1
index:  1107 ; vehicle:  SKID ; total accidents:  2
index:  1108 ; vehicle:  bed ; total accidents:  1
index:  1109 ; vehicle:  city ; total accidents:  1
index:  1110 ; vehicle:  Jeep ; total accidents:  1
index:  1111 ; vehicle:  conv ; total accidents:  1
index:  1112 ; vehicle:  case ; total accidents:  1
index:  1113 ; vehicle:  TRACK ; total accidents:  1
index:  1114 ; vehicle:  Road ; total accidents:  1
index:  1115 ; vehicle:  conta ; total accidents:  1
index:  1116 ; vehicle:  car c ; total accidents:  1
index:  1117 ; vehicle:  EMS B ; total accidents:  1
index:  1118 ; vehicle:  scava ; total accidents:  1
index:  1119 ; vehicle:  72000 ; total accidents:  1
index:  1120 ; vehicle:  Small ; total accidents:  1
index:  1121 ; vehicle:  JOHND ; total accidents:  1
index:  1122 ; vehicle:  TKP ; total accidents:  1
index:  1123 ; vehicle:  Refri ; total accidents:  1
index:  1124 ; vehicle:  VMS T ; total accidents:  1
index:  1125 ; vehicle:  Laund ; total accidents:  1
index:  1126 ; vehicle:  FEDER ; total accidents:  1
index:  1127 ; vehicle:  DSNY ; total accidents:  1
index:  1128 ; vehicle:  e-BIK ; total accidents:  1
index:  1129 ; vehicle:  Mopen ; total accidents:  1
index:  1130 ; vehicle:  U-TRU ; total accidents:  1
index:  1131 ; vehicle:  CRWZK ; total accidents:  1
index:  1132 ; vehicle:  front ; total accidents:  1
index:  1133 ; vehicle:  MTRIZ ; total accidents:  1
index:  1134 ; vehicle:  E-SCO ; total accidents:  2
index:  1135 ; vehicle:  ENCLO ; total accidents:  1
index:  1136 ; vehicle:  HAND ; total accidents:  1
index:  1137 ; vehicle:  c7c ; total accidents:  1
index:  1138 ; vehicle:  E Bik ; total accidents:  2
index:  1139 ; vehicle:  VAN C ; total accidents:  1
index:  1140 ; vehicle:  lift ; total accidents:  1
index:  1141 ; vehicle:  MAN B ; total accidents:  1
index:  1142 ; vehicle:  nyfd ; total accidents:  1
index:  1143 ; vehicle:  RAM ; total accidents:  1
index:  1144 ; vehicle:  JLG L ; total accidents:  1
index:  1145 ; vehicle:  ALUMI ; total accidents:  1
index:  1146 ; vehicle:  CAT32 ; total accidents:  1
index:  1147 ; vehicle:  rep ; total accidents:  1
index:  1148 ; vehicle:  MTA b ; total accidents:  1
index:  1149 ; vehicle:  sprin ; total accidents:  1
index:  1150 ; vehicle:  Train ; total accidents:  1
index:  1151 ; vehicle:  DETAC ; total accidents:  1
index:  1152 ; vehicle:  Depar ; total accidents:  1
index:  1153 ; vehicle:  boom ; total accidents:  1
index:  1154 ; vehicle:  ASPHA ; total accidents:  1
index:  1155 ; vehicle:  BUMP ; total accidents:  1
index:  1156 ; vehicle:  52? t ; total accidents:  1
index:  1157 ; vehicle:  Liebh ; total accidents:  1
index:  1158 ; vehicle:  Dirt ; total accidents:  1
index:  1159 ; vehicle:  N/a ; total accidents:  1
index:  1160 ; vehicle:  MOBIL ; total accidents:  1
index:  1161 ; vehicle:  mo-pe ; total accidents:  1
index:  1162 ; vehicle:  RAZOR ; total accidents:  1
index:  1163 ; vehicle:  BROWN ; total accidents:  1
index:  1164 ; vehicle:  11 PA ; total accidents:  1
index:  1165 ; vehicle:  LADDE ; total accidents:  1
index:  1166 ; vehicle:  Sciss ; total accidents:  1
index:  1167 ; vehicle:  E-SKA ; total accidents:  1
index:  1168 ; vehicle:  spec- ; total accidents:  1
index:  1169 ; vehicle:  Pedic ; total accidents:  1
index:  1170 ; vehicle:  EMT ; total accidents:  1
index:  1171 ; vehicle:  GAS T ; total accidents:  1
index:  1172 ; vehicle:  2 HOR ; total accidents:  1
index:  1173 ; vehicle:  Postal Veh ; total accidents:  1
index:  1174 ; vehicle:  street swe ; total accidents:  2
index:  1175 ; vehicle:  PALLET JAC ; total accidents:  1
index:  1176 ; vehicle:  FD TRUCK ; total accidents:  4
index:  1177 ; vehicle:  Utility ; total accidents:  1
index:  1178 ; vehicle:  Food Cart ; total accidents:  1
index:  1179 ; vehicle:  00000 ; total accidents:  1
index:  1180 ; vehicle:  boom crane ; total accidents:  1
index:  1181 ; vehicle:  SKIDSTEERL ; total accidents:  1
index:  1182 ; vehicle:  Chevy ; total accidents:  1
index:  1183 ; vehicle:  Tow truck ; total accidents:  2
index:  1184 ; vehicle:  TRACTOR TR ; total accidents:  5
index:  1185 ; vehicle:  CITY OF NE ; total accidents:  1
index:  1186 ; vehicle:  VENDOR CHA ; total accidents:  1
index:  1187 ; vehicle:  semi-trail ; total accidents:  1
index:  1188 ; vehicle:  Mobile foo ; total accidents:  1
index:  1189 ; vehicle:  school bus ; total accidents:  3
index:  1190 ; vehicle:  PICK RD ; total accidents:  1
index:  1191 ; vehicle:  delivery ; total accidents:  1
index:  1192 ; vehicle:  HINO TANK ; total accidents:  1
index:  1193 ; vehicle:  Short Bus ; total accidents:  1
index:  1194 ; vehicle:  SCOTTER ; total accidents:  1
index:  1195 ; vehicle:  NYC fire t ; total accidents:  1
index:  1196 ; vehicle:  POSTAL CAR ; total accidents:  1
index:  1197 ; vehicle:  600AJ ; total accidents:  1
index:  1198 ; vehicle:  omt ; total accidents:  1
index:  1199 ; vehicle:  SPINTER VA ; total accidents:  1
index:  1200 ; vehicle:  BLU BUS ; total accidents:  1
index:  1201 ; vehicle:  ambulence ; total accidents:  1
index:  1202 ; vehicle:  Livery Omn ; total accidents:  1
index:  1203 ; vehicle:  NYC DOT ; total accidents:  1
index:  1204 ; vehicle:  TANK WH ; total accidents:  1
index:  1205 ; vehicle:  power shov ; total accidents:  1
index:  1206 ; vehicle:  Road Sweep ; total accidents:  1
index:  1207 ; vehicle:  City MTA b ; total accidents:  1
index:  1208 ; vehicle:  Pumper tru ; total accidents:  1
index:  1209 ; vehicle:  trailor ; total accidents:  1
index:  1210 ; vehicle:  armored tr ; total accidents:  1
index:  1211 ; vehicle:  SPRINTER V ; total accidents:  2
index:  1212 ; vehicle:  mail truck ; total accidents:  1
index:  1213 ; vehicle:  Forklift t ; total accidents:  1
index:  1214 ; vehicle:  self insur ; total accidents:  2
index:  1215 ; vehicle:  constructi ; total accidents:  3
index:  1216 ; vehicle:  US Postal ; total accidents:  1
index:  1217 ; vehicle:  E-SCOOTER ; total accidents:  11
index:  1218 ; vehicle:  Electric S ; total accidents:  1
index:  1219 ; vehicle:  ESCAVATOR ; total accidents:  1
index:  1220 ; vehicle:  18 WEELER ; total accidents:  1
index:  1221 ; vehicle:  SWEEPER ; total accidents:  1
index:  1222 ; vehicle:  GLNEN ; total accidents:  1
index:  1223 ; vehicle:  Light trai ; total accidents:  1
index:  1224 ; vehicle:  itas ; total accidents:  1
index:  1225 ; vehicle:  Golf Cart ; total accidents:  1
index:  1226 ; vehicle:  PICK-UP TR ; total accidents:  2
index:  1227 ; vehicle:  Dirt bike ; total accidents:  1
index:  1228 ; vehicle:  Flat bed ; total accidents:  2
index:  1229 ; vehicle:  DELIVERY V ; total accidents:  1
index:  1230 ; vehicle:  RDS ; total accidents:  1

index:  1231 ; vehicle:  ACCESS A R ; total accidents:  1
index:  1232 ; vehicle:  JETSKI ; total accidents:  1
index:  1233 ; vehicle:  AMAZON SPR ; total accidents:  1
index:  1234 ; vehicle:  Tree cutte ; total accidents:  1
index:  1235 ; vehicle:  Toyota ; total accidents:  1
index:  1236 ; vehicle:  BOB CAT ; total accidents:  1
index:  1237 ; vehicle:  GLP050VXEV ; total accidents:  1
index:  1238 ; vehicle:  ESCOVATOR ; total accidents:  1
index:  1239 ; vehicle:  Delivery t ; total accidents:  2
index:  1240 ; vehicle:  Razor scoo ; total accidents:  1
index:  1241 ; vehicle:  ICE CREAM ; total accidents:  3
index:  1242 ; vehicle:  HAUL FOR H ; total accidents:  1
index:  1243 ; vehicle:  Pickup ; total accidents:  3
index:  1244 ; vehicle:  Pick Truck ; total accidents:  1
index:  1245 ; vehicle:  VEHICLE 2 ; total accidents:  1
index:  1246 ; vehicle:  FLAT BED ; total accidents:  1
index:  1247 ; vehicle:  EMS TRUCK ; total accidents:  3
index:  1248 ; vehicle:  Electric s ; total accidents:  1
index:  1249 ; vehicle:  NYC BUS ; total accidents:  1
index:  1250 ; vehicle:  E-SKATEBOA ; total accidents:  1
index:  1251 ; vehicle:  FRIEGHTLIN ; total accidents:  1
index:  1252 ; vehicle:  PALFINGER ; total accidents:  1
index:  1253 ; vehicle:  Moped Scoo ; total accidents:  1
index:  1254 ; vehicle:  INTERNATIO ; total accidents:  1
index:  1255 ; vehicle:  ELECTRIC M ; total accidents:  2
index:  1256 ; vehicle:  e-bike ; total accidents:  1
index:  1257 ; vehicle:  ESCOOTER ; total accidents:  1
index:  1258 ; vehicle:  MTA Truck ; total accidents:  2
index:  1259 ; vehicle:  Skateboard ; total accidents:  1
index:  1260 ; vehicle:  4dsd ; total accidents:  1
index:  1261 ; vehicle:  John Deere ; total accidents:  1
index:  1262 ; vehicle:  Dump Truck ; total accidents:  1
index:  1263 ; vehicle:  uhaul truc ; total accidents:  1
index:  1264 ; vehicle:  DIRTBIKE ; total accidents:  2
index:  1265 ; vehicle:  TRUCK TRAI ; total accidents:  1
index:  1266 ; vehicle:  MOPED SCOO ; total accidents:  1
index:  1267 ; vehicle:  uknown ; total accidents:  1
index:  1268 ; vehicle:  Tilt tande ; total accidents:  1
index:  1269 ; vehicle:  BACKHOE LO ; total accidents:  1
index:  1270 ; vehicle:  MINI VAN ; total accidents:  1
index:  1271 ; vehicle:  Fleet ; total accidents:  1
index:  1272 ; vehicle:  LEFT THE S ; total accidents:  1
index:  1273 ; vehicle:  boom lift ; total accidents:  1
index:  1274 ; vehicle:  NYC ACS Va ; total accidents:  1
index:  1275 ; vehicle:  MAILTRUCK ; total accidents:  1
index:  1276 ; vehicle:  Flatbed ; total accidents:  1
index:  1277 ; vehicle:  Sweeper ; total accidents:  1
index:  1278 ; vehicle:  E SCOOTER ; total accidents:  1
index:  1279 ; vehicle:  motor scoo ; total accidents:  2
index:  1280 ; vehicle:  UNKNOWN VE ; total accidents:  2
index:  1281 ; vehicle:  Escavator ; total accidents:  1
index:  1282 ; vehicle:  motorbike ; total accidents:  1
index:  1283 ; vehicle:  fdny ladde ; total accidents:  2
index:  1284 ; vehicle:  Delivery T ; total accidents:  3
index:  1285 ; vehicle:  Car traile ; total accidents:  2
index:  1286 ; vehicle:  CAR TRAILE ; total accidents:  1
index:  1287 ; vehicle:  Amazon tru ; total accidents:  1
index:  1288 ; vehicle:  GAS SCOOTE ; total accidents:  3
index:  1289 ; vehicle:  Truck cran ; total accidents:  1
index:  1290 ; vehicle:  courier ; total accidents:  1
index:  1291 ; vehicle:  e-sooter ; total accidents:  1
index:  1292 ; vehicle:  WORKH UTIL ; total accidents:  1
index:  1293 ; vehicle:  MOTORCYCLE ; total accidents:  3
index:  1294 ; vehicle:  E- MOTOR B ; total accidents:  1
index:  1295 ; vehicle:  FED EX ; total accidents:  2
index:  1296 ; vehicle:  PICKUP TOW ; total accidents:  1
index:  1297 ; vehicle:  wheel barr ; total accidents:  1
index:  1298 ; vehicle:  ESU REP ; total accidents:  1
index:  1299 ; vehicle:  POSTAL SER ; total accidents:  1
index:  1300 ; vehicle:  Motorizeds ; total accidents:  1
index:  1301 ; vehicle:  AMBULANCE` ; total accidents:  1
index:  1302 ; vehicle:  FREIGHT ; total accidents:  1
index:  1303 ; vehicle:  police veh ; total accidents:  1
index:  1304 ; vehicle:  e-scooter ; total accidents:  1
index:  1305 ; vehicle:  DEL ; total accidents:  1
index:  1306 ; vehicle:  Ny Ems ; total accidents:  1
index:  1307 ; vehicle:  street cle ; total accidents:  1
index:  1308 ; vehicle:  PEDI CAB ; total accidents:  1
index:  1309 ; vehicle:  RENTED BOO ; total accidents:  1
index:  1310 ; vehicle:  Comm Food ; total accidents:  1
index:  1311 ; vehicle:  CADET ; total accidents:  1
index:  1312 ; vehicle:  CHERRY PIC ; total accidents:  1
index:  1313 ; vehicle:  USPCS Truc ; total accidents:  1
index:  1314 ; vehicle:  Sprinter V ; total accidents:  1
index:  1315 ; vehicle:  Uhaul truc ; total accidents:  1
index:  1316 ; vehicle:  NYC TRANSI ; total accidents:  1
index:  1317 ; vehicle:  Tk ; total accidents:  1
index:  1318 ; vehicle:  EXCAVATOR ; total accidents:  2
index:  1319 ; vehicle:  Command Po ; total accidents:  1
index:  1320 ; vehicle:  road sweep ; total accidents:  1
index:  1321 ; vehicle:  usps self ; total accidents:  1
index:  1322 ; vehicle:  Power shov ; total accidents:  1
index:  1323 ; vehicle:  sanitation ; total accidents:  1
index:  1324 ; vehicle:  BOBCAT ; total accidents:  1
index:  1325 ; vehicle:  fork lift ; total accidents:  2
index:  1326 ; vehicle:  COMMAND PO ; total accidents:  1
index:  1327 ; vehicle:  Plow  truc ; total accidents:  1
index:  1328 ; vehicle:  SUBN TN ; total accidents:  1
index:  1329 ; vehicle:  PLOW TRUCK ; total accidents:  1
index:  1330 ; vehicle:  Garbage tr ; total accidents:  1
index:  1331 ; vehicle:  Caterpilla ; total accidents:  1
index:  1332 ; vehicle:  mta bus  4 ; total accidents:  1
index:  1333 ; vehicle:  AMbulance ; total accidents:  1
index:  1334 ; vehicle:  AMBULETTE ; total accidents:  1
index:  1335 ; vehicle:  Util. ; total accidents:  1
index:  1336 ; vehicle:  Garbage Tr ; total accidents:  1
index:  1337 ; vehicle:  SCHOOL VAN ; total accidents:  1
index:  1338 ; vehicle:  INDUSTRIAL ; total accidents:  1
index:  1339 ; vehicle:  bucket tru ; total accidents:  1
index:  1340 ; vehicle:  REVEL SCOO ; total accidents:  1
index:  1341 ; vehicle:  Rental Tru ; total accidents:  1
index:  1342 ; vehicle:  FOR VAN ; total accidents:  1
index:  1343 ; vehicle:  Suburban ; total accidents:  2
index:  1344 ; vehicle:  skateboard ; total accidents:  2
index:  1345 ; vehicle:  MOTORED SC ; total accidents:  1
index:  1346 ; vehicle:  uni e-bike ; total accidents:  1
index:  1347 ; vehicle:  U Haul Tru ; total accidents:  1
index:  1348 ; vehicle:  ROADROLLER ; total accidents:  1
index:  1349 ; vehicle:  COLLECTION ; total accidents:  1
index:  1350 ; vehicle:  basic psd ; total accidents:  1
index:  1351 ; vehicle:  WHEELCHAIR ; total accidents:  2
index:  1352 ; vehicle:  util truck ; total accidents:  1
index:  1353 ; vehicle:  work van ; total accidents:  1
index:  1354 ; vehicle:  MOPAD ; total accidents:  1
index:  1355 ; vehicle:  NICE BUS ; total accidents:  1
index:  1356 ; vehicle:  bmw ; total accidents:  1
index:  1357 ; vehicle:  FDNY RIG ; total accidents:  1
index:  1358 ; vehicle:  WH ; total accidents:  1
index:  1359 ; vehicle:  COURIER VA ; total accidents:  1
index:  1360 ; vehicle:  FDNY truck ; total accidents:  1
index:  1361 ; vehicle:  toolcat ; total accidents:  1
index:  1362 ; vehicle:  Uhaul Truc ; total accidents:  1
index:  1363 ; vehicle:  FDNY AMBU ; total accidents:  1
index:  1364 ; vehicle:  SPECIAL PU ; total accidents:  1
index:  1365 ; vehicle:  cat payloa ; total accidents:  1
index:  1366 ; vehicle:  dirt bike ; total accidents:  1
index:  1367 ; vehicle:  FOOD CART ; total accidents:  1
index:  1368 ; vehicle:  gas bicycl ; total accidents:  1
index:  1369 ; vehicle:  M21 ; total accidents:  1
index:  1370 ; vehicle:  Pedestrian ; total accidents:  1
index:  1371 ; vehicle:  FIRE TURCK ; total accidents:  1
index:  1372 ; vehicle:  TRUCK LADD ; total accidents:  1
index:  1373 ; vehicle:  ORANGE JLG ; total accidents:  1
index:  1374 ; vehicle:  dirtbike ; total accidents:  1
index:  1375 ; vehicle:  motorhome ; total accidents:  1

index:  1376 ; vehicle:  BOOM LIFT/ ; total accidents:  1
index:  1377 ; vehicle:  STAKE TRUC ; total accidents:  1
index:  1378 ; vehicle:  scooter ga ; total accidents:  1
index:  1379 ; vehicle:  tractor ; total accidents:  2
index:  1380 ; vehicle:  Scooter no ; total accidents:  1
index:  1381 ; vehicle:  revel ; total accidents:  1
index:  1382 ; vehicle:  Golf cart ; total accidents:  1
index:  1383 ; vehicle:  Ambiance ; total accidents:  1
index:  1384 ; vehicle:  UPS Van ; total accidents:  1
index:  1385 ; vehicle:  AERIAL LIF ; total accidents:  1
index:  1386 ; vehicle:  AMBULAMCE ; total accidents:  1
index:  1387 ; vehicle:  DOLLAR VAN ; total accidents:  1
index:  1388 ; vehicle:  Chevy carg ; total accidents:  1
index:  1389 ; vehicle:  UKNOWN ; total accidents:  1
index:  1390 ; vehicle:  Road sweep ; total accidents:  1
index:  1391 ; vehicle:  spc ; total accidents:  1
index:  1392 ; vehicle:  Marked Van ; total accidents:  1
index:  1393 ; vehicle:  skate boar ; total accidents:  1
index:  1394 ; vehicle:  Fed ex van ; total accidents:  1
index:  1395 ; vehicle:  Ems truck ; total accidents:  1
index:  1396 ; vehicle:  Oil Tanker ; total accidents:  1
index:  1397 ; vehicle:  delivery w ; total accidents:  1
index:  1398 ; vehicle:  MOPPED ; total accidents:  1
index:  1399 ; vehicle:  Pick Up Tr ; total accidents:  1
index:  1400 ; vehicle:  Gator ; total accidents:  1
index:  1401 ; vehicle:  DL ; total accidents:  1
index:  1402 ; vehicle:  EZ GO ; total accidents:  1
index:  1403 ; vehicle:  MTABUS ; total accidents:  1
index:  1404 ; vehicle:  ESCOOTER S ; total accidents:  1
index:  1405 ; vehicle:  PEDICAB ; total accidents:  1
index:  1406 ; vehicle:  MTA NYC BU ; total accidents:  1
index:  1407 ; vehicle:  CITY VEHIC ; total accidents:  1
index:  1408 ; vehicle:  Revel Mo'e ; total accidents:  1
index:  1409 ; vehicle:  excavator ; total accidents:  1
index:  1410 ; vehicle:  bay crane ; total accidents:  1
index:  1411 ; vehicle:  Moped clas ; total accidents:  1
index:  1412 ; vehicle:  GAS MOPED ; total accidents:  1
index:  1413 ; vehicle:  GMC DELIVE ; total accidents:  1
index:  1414 ; vehicle:  FORD TRANS ; total accidents:  1
index:  1415 ; vehicle:  Moped scoo ; total accidents:  1
index:  1416 ; vehicle:  MO PED ; total accidents:  1
index:  1417 ; vehicle:  wheel load ; total accidents:  1
index:  1418 ; vehicle:  Unknown ve ; total accidents:  1
index:  1419 ; vehicle:  LEFT SCENE ; total accidents:  1
index:  1420 ; vehicle:  SHORT SCHO ; total accidents:  1
index:  1421 ; vehicle:  Utility ca ; total accidents:  1
index:  1422 ; vehicle:  50 CC Moto ; total accidents:  1
index:  1423 ; vehicle:  fedex truc ; total accidents:  1
index:  1424 ; vehicle:  Lateral Tr ; total accidents:  1
index:  1425 ; vehicle:  HOVERBOARD ; total accidents:  1
index:  1426 ; vehicle:  Front End ; total accidents:  1
index:  1427 ; vehicle:  EMBULANCE ; total accidents:  1
index:  1428 ; vehicle:  back ho ; total accidents:  1
index:  1429 ; vehicle:  REVEL MOPE ; total accidents:  1
index:  1430 ; vehicle:  Trailer no ; total accidents:  1
index:  1431 ; vehicle:  Fedex Box ; total accidents:  1
index:  1432 ; vehicle:  Self insur ; total accidents:  1
index:  1433 ; vehicle:  NYC FIRE T ; total accidents:  1
index:  1434 ; vehicle:  999 ; total accidents:  1
index:  1435 ; vehicle:  TOWTRUCK ; total accidents:  1
index:  1436 ; vehicle:  Food cart ; total accidents:  1
index:  1437 ; vehicle:  ESCAVATER ; total accidents:  1
index:  1438 ; vehicle:  SPRINTER ; total accidents:  1
index:  1439 ; vehicle:  DOT VEHICL ; total accidents:  1
index:  1440 ; vehicle:  Ltrl ; total accidents:  1
index:  1441 ; vehicle:  NYCFIREDEP ; total accidents:  1
index:  1442 ; vehicle:  BLUE CHEVY ; total accidents:  1
Execution time in seconds: 7024.827116012573

In [71]:
vehicles_df.to_csv("vehicles_calculations.csv")

## Reasons for Collisions

In [72]:
tempDf1 = pd.DataFrame()
tempDf2 = pd.DataFrame()

tempDf1["REASONS"] = clean_df["CONTRIBUTING FACTOR VEHICLE 1"]
tempDf2["REASONS"] = clean_df["CONTRIBUTING FACTOR VEHICLE 2"]

In [73]:
reasons_df = pd.concat([tempDf1, tempDf2], ignore_index=True)

In [74]:
reasons_df = reasons_df.dropna()

In [75]:
reasons_df = reasons_df.drop_duplicates()

In [76]:
reasons_df = reasons_df.reset_index(drop=True)

In [77]:
reasons_df.head()

                          REASONS
0     Traffic Control Disregarded
1                     Unspecified
2  Driver Inattention/Distraction
3              Turning Improperly
4                Backing Unsafely

In [78]:
# Count how many accidents occur by reason type
# Because there are two columns for reasons, you'll need to take both columns in
startTime = time.time()


results = []
for i in range(reasons_df.shape[0]):
    counter = 0
    def countingReasons(row, reason: str):
        global counter
        if row["CONTRIBUTING FACTOR VEHICLE 1"] == reason and row["CONTRIBUTING FACTOR VEHICLE 2"] == reason:
            #print("\nreason: ", reasons_df.iloc[i]["REASONS"], "\nreason 1: ", row["CONTRIBUTING FACTOR VEHICLE 1"], "\nreason 2: ", row["CONTRIBUTING FACTOR VEHICLE 2"], "\ncounting up 2", "\n========")
            counter += 2
        elif row["CONTRIBUTING FACTOR VEHICLE 1"] == reason or row["VEHICLE TYPE CODE 2"] == reason:
            #print("\nreason: ", reasons_df.iloc[i]["REASONS"], "\nreason 1: ", row["CONTRIBUTING FACTOR VEHICLE 1"], "\nreason 2: ", row["CONTRIBUTING FACTOR VEHICLE 2"], "\ncounting up 1", "\n========")
            counter += 1
        
    clean_df.apply(countingReasons, axis=1, args=(reasons_df.iloc[i]["REASONS"], ))
    results.append(counter)
    print("reason: ", reasons_df.iloc[i]["REASONS"], "; total: ", counter)
    
tempDf = pd.DataFrame(results, columns=["TOTAL"])
reasons_df["TOTAL"] = tempDf["TOTAL"]


executionTime = (time.time() - startTime)
print('Execution time in seconds: ' + str(executionTime))

reason:  Traffic Control Disregarded ; total:  12746
reason:  Unspecified ; total:  230521
reason:  Driver Inattention/Distraction ; total:  157214
reason:  Turning Improperly ; total:  14219
reason:  Backing Unsafely ; total:  30393
reason:  Unsafe Speed ; total:  9094
reason:  Failure to Yield Right-of-Way ; total:  43769
reason:  Other Vehicular ; total:  20230
reason:  Following Too Closely ; total:  33179
reason:  Passing or Lane Usage Improper ; total:  26102
reason:  Unsafe Lane Changing ; total:  12960
reason:  Alcohol Involvement ; total:  6719
reason:  Pavement Defective ; total:  613
reason:  Driver Inexperience ; total:  10281
reason:  Passing Too Closely ; total:  26914
reason:  Steering Failure ; total:  888
reason:  Reaction to Uninvolved Vehicle ; total:  6557
reason:  View Obstructed/Limited ; total:  5489
reason:  Pedestrian/Bicyclist/Other Pedestrian Error/Confusion ; total:  4333
reason:  Fell Asleep ; total:  1594
reason:  Aggressive Driving/Road Rage ; total:  2948
reason:  Pavement Slippery ; total:  4494
reason:  Failure to Keep Right ; total:  730
reason:  Accelerator Defective ; total:  358
reason:  Brakes Defective ; total:  1975
reason:  Illnes ; total:  651
reason:  Fatigued/Drowsy ; total:  542
reason:  Passenger Distraction ; total:  2084
reason:  Windshield Inadequate ; total:  12
reason:  Oversized Vehicle ; total:  3847
reason:  Lane Marking Improper/Inadequate ; total:  321
reason:  Animals Action ; total:  452
reason:  Obstruction/Debris ; total:  1016
reason:  Glare ; total:  1059
reason:  Tire Failure/Inadequate ; total:  525
reason:  Driverless/Runaway Vehicle ; total:  644
reason:  Tinted Windows ; total:  59
reason:  Physical Disability ; total:  162
reason:  Outside Car Distraction ; total:  1225
reason:  Traffic Control Device Improper/Non-Working ; total:  302
reason:  Eating or Drinking ; total:  48
reason:  Drugs (illegal) ; total:  358
reason:  Headlights Defective ; total:  40
reason:  Lost Consciousness ; total:  624
reason:  Cell Phone (hand-Held) ; total:  206
reason:  Other Electronic Device ; total:  66
reason:  Cell Phone (hands-free) ; total:  19
reason:  Texting ; total:  19
reason:  Other Lighting Defects ; total:  58
reason:  Using On Board Navigation Device ; total:  47
reason:  Vehicle Vandalism ; total:  62
reason:  Prescription Medication ; total:  54
reason:  Tow Hitch Defective ; total:  65
reason:  Shoulders Defective/Improper ; total:  18
reason:  Listening/Using Headphones ; total:  6
Execution time in seconds: 271.70731687545776

In [79]:
reasons_df.to_csv("reasons_for_collisions.csv")

## By Year

How many collisions by year?

In [80]:
split_clean_df = clean_df.copy()

In [81]:
#trim string to just be the year
split_clean_df[["MONTH", "DAY", "YEAR"]] = split_clean_df["CRASH DATE"].str.split("/", expand=True)

In [82]:
crashDate_df = pd.DataFrame()
crashDate_df["YEAR"] = split_clean_df["YEAR"]

In [83]:
crashDate_df = crashDate_df.drop_duplicates()

In [84]:
crashDate_df = crashDate_df.reset_index(drop=True)

In [85]:
crashDate_df.head()

   YEAR
0  2017
1  2018
2  2019
3  2020
4  2021

How many accidents occured by year?

In [86]:
# Count how many accidents occur in these buroughs
results = []
for i in range(crashDate_df.shape[0]):
    counter = 0
    def countingAccidentsByYear(row, year: str):
        global counter
        if row["YEAR"] == year:
            counter += 1
    split_clean_df.apply(countingAccidentsByYear, axis=1, args=(crashDate_df.iloc[i]["YEAR"], ))
    results.append(counter)
    print("year: ", crashDate_df.iloc[i]["YEAR"], "; total accidents: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_ACCIDENTS_YEAR"])
crashDate_df["NUMBER_OF_ACCIDENTS_YEAR"] = tempDf["NUMBER_OF_ACCIDENTS_YEAR"]

year:  2017 ; total accidents:  138473
year:  2018 ; total accidents:  144769
year:  2019 ; total accidents:  133049
year:  2020 ; total accidents:  71621
year:  2021 ; total accidents:  70064

In [87]:
crashDate_df.head()

   YEAR  NUMBER_OF_ACCIDENTS_YEAR
0  2017                    138473
1  2018                    144769
2  2019                    133049
3  2020                     71621
4  2021                     70064

How many people injured by year?

In [88]:
# Count how many accidents occur in these buroughs
results = []
for i in range(crashDate_df.shape[0]):
    counter = 0
    def countingInjuriesByYear(row, year: str):
        global counter
        if row["YEAR"] == year:
            counter += row["NUMBER OF PERSONS INJURED"]
    split_clean_df.apply(countingInjuriesByYear, axis=1, args=(crashDate_df.iloc[i]["YEAR"], ))
    results.append(counter)
    print("year: ", crashDate_df.iloc[i]["YEAR"], "; total injuries: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_INJURIES_YEAR"])
crashDate_df["NUMBER_OF_INJURIES_YEAR"] = tempDf["NUMBER_OF_INJURIES_YEAR"]

year:  2017 ; total injuries:  34138.0
year:  2018 ; total injuries:  36276.0
year:  2019 ; total injuries:  36333.0
year:  2020 ; total injuries:  25896.0
year:  2021 ; total injuries:  30667.0

In [89]:
crashDate_df.head()

   YEAR  NUMBER_OF_ACCIDENTS_YEAR  NUMBER_OF_INJURIES_YEAR
0  2017                    138473                  34138.0
1  2018                    144769                  36276.0
2  2019                    133049                  36333.0
3  2020                     71621                  25896.0
4  2021                     70064                  30667.0

How many people killed by year?

In [90]:
# Count how many accidents occur in these buroughs
results = []
for i in range(crashDate_df.shape[0]):
    counter = 0
    def countingDeathsByYear(row, year: str):
        global counter
        if row["YEAR"] == year:
            counter += row["NUMBER OF PERSONS KILLED"]
    split_clean_df.apply(countingDeathsByYear, axis=1, args=(crashDate_df.iloc[i]["YEAR"], ))
    results.append(counter)
    print("year: ", crashDate_df.iloc[i]["YEAR"], "; total deaths: ", counter)
    
tempDf = pd.DataFrame(results, columns=["NUMBER_OF_DEATHS_YEAR"])
crashDate_df["NUMBER_OF_DEATHS_YEAR"] = tempDf["NUMBER_OF_DEATHS_YEAR"]

year:  2017 ; total deaths:  127.0
year:  2018 ; total deaths:  135.0
year:  2019 ; total deaths:  134.0
year:  2020 ; total deaths:  142.0
year:  2021 ; total deaths:  128.0

In [91]:
crashDate_df.head()

,YEAR,NUMBER_OF_ACCIDENTS_YEAR,NUMBER_OF_INJURIES_YEAR,NUMBER_OF_DEATHS_YEAR
0,2017,138473,34138.0,127.0
1,2018,144769,36276.0,135.0
2,2019,133049,36333.0,134.0
3,2020,71621,25896.0,142.0
4,2021,70064,30667.0,128.0

In [92]:
crashDate_df.to_csv("collisionsByYear_calculations.csv")